/**
 * A1 (Beginner) grammar — topics 16-21: Present Perfect, Plurals / Countables,
 * Some / any, Articles, Adjectives / Adverbs, Adjective degrees.
 * Written by Claude as a DRAFT for teacher review (imported unpublished).
 * APPEND-ONLY: never reorder or delete items once shipped — progress keys on
 * (topic slug, kind, position). Validated by tests/grammar-content.test.ts.
 */
import type { GrammarItemContent, GrammarTopicContent } from "@shared/grammar/types";

/** One sentence: Uzbek prompt, model English, traps, and other correct answers. */
const s = (uz: string, en: string, traps: string[], alt?: string[]): GrammarItemContent =>
  alt ? { uz, en, traps, alt } : { uz, en, traps };

/* ───────────────────────────── 16. Present Perfect ───────────────────────────── */

const PRESENT_PERFECT: GrammarTopicContent = {
  slug: "a1-present-perfect",
  level: "A1",
  position: 16,
  title: { en: "Present Perfect", uz: "Present Perfect (tajriba, natija)" },
  explanation: {
    uz: [
      "Present Perfect: have / has + fe'lning 3-shakli (V3): I have seen, she has eaten, they have finished.",
      "Hayotiy tajriba (qachonligi muhim emas): I have been to London = Men Londonda bo'lganman.",
      "Ever (hech) so'roqda, never (hech qachon) inkor ma'noda: Have you ever eaten plov? I have never seen snow.",
      "Just - hozirgina, already - allaqachon, yet - hali (inkor va so'roqda, gap oxirida): I haven't finished yet.",
      "Aniq o'tgan vaqt (yesterday, last year) bo'lsa Past Simple ishlatiladi: I saw him yesterday (have seen emas).",
      "Ko'p uchraydigan V3: be - been, go - gone / been, see - seen, eat - eaten, do - done, buy - bought, write - written, finish - finished.",
    ].join("\n"),
    pattern: "I / you / we / they + have + V3 | he / she / it + has + V3 · not: haven't / hasn't + V3 · question: Have / Has + subject + V3 …? · ever, never, just, already, yet",
    examples: [
      { en: "I have been to Samarkand.", uz: "Men Samarqandda bo'lganman." },
      { en: "She has just finished her homework.", uz: "U hozirgina uy vazifasini tugatdi." },
      { en: "Have you ever eaten sushi?", uz: "Siz hech sushi yeganmisiz?" },
      { en: "We haven't seen this film yet.", uz: "Biz bu filmni hali ko'rmadik." },
    ],
  },
  build: [
    s("Men Samarqandda bo'lganman.", "I have been to Samarkand.", ["was"], ["I've been to Samarkand."]),
    s("Madina Londonda bo'lgan.", "Madina has been to London.", ["have"], ["Madina's been to London."]),
    s("Biz bu filmni ko'rganmiz.", "We have seen this film.", ["saw"], ["We have seen this movie.", "We've seen this film.", "We've seen this movie."]),
    s("Ular yangi uy sotib olishdi.", "They have bought a new house.", ["buyed"], ["They've bought a new house."]),
    s("Men kalitlarimni yo'qotib qo'ydim.", "I have lost my keys.", ["losed"], ["I've lost my keys."]),
    s("Ali uy vazifasini qilib bo'ldi.", "Ali has done his homework.", ["did"], ["Ali has finished his homework."]),
    s("Men hozirgina nonushta qildim.", "I have just had breakfast.", ["has"], ["I've just had breakfast.", "I have just eaten breakfast.", "I've just eaten breakfast."]),
    s("Avtobus hozirgina ketdi.", "The bus has just left.", ["have"]),
    s("Men allaqachon xatni yozib bo'ldim.", "I have already written the letter.", ["wrote"], ["I've already written the letter."]),
    s("Film allaqachon boshlandi.", "The film has already started.", ["have"], ["The movie has already started.", "The film has already begun.", "The movie has already begun."]),
    s("Men hech qachon qor ko'rmaganman.", "I have never seen snow.", ["saw"], ["I've never seen snow."]),
    s("Zarina hech qachon samolyotda uchmagan.", "Zarina has never flown on a plane.", ["flied"], ["Zarina has never been on a plane."]),
    s("Biz hali tushlik qilmadik.", "We haven't had lunch yet.", ["hasn't"], ["We haven't eaten lunch yet."]),
    s("Sardor hali kelmadi.", "Sardor hasn't come yet.", ["haven't"], ["Sardor hasn't arrived yet."]),
    s("Men hali bu kitobni o'qimadim.", "I haven't read this book yet.", ["didn't"]),
    s("Ular hali ishni tugatishmadi.", "They haven't finished the work yet.", ["hasn't"], ["They haven't finished their work yet."]),
    s("Siz hech palov yeganmisiz?", "Have you ever eaten plov?", ["ate"], ["Have you ever tried plov?"]),
    s("Siz hech Buxoroda bo'lganmisiz?", "Have you ever been to Bukhara?", ["was"]),
    s("Malika uy vazifasini qilib bo'ldimi?", "Has Malika done her homework?", ["did"], ["Has Malika finished her homework?"]),
    s("Xatimni oldingmi?", "Have you received my letter?", ["receive"], ["Have you got my letter?"]),
    s("Ular hali kelishdimi?", "Have they arrived yet?", ["arrive"], ["Have they come yet?"]),
    s("Sen hech ot minganmisan? Ha, minganman.", "Have you ever ridden a horse? Yes, I have.", ["rode"]),
    s("Ali Toshkentda bo'lganmi? Yo'q, bo'lmagan.", "Has Ali been to Tashkent? No, he hasn't.", ["was"]),
    s("Men bu odamni oldin ko'rganman.", "I have seen this man before.", ["saw"], ["I've seen this man before.", "I have seen this person before."]),
    s("Otam yangi mashina sotib oldi.", "My father has bought a new car.", ["have"], ["My dad has bought a new car.", "My father's bought a new car."]),
    s("Men uch marta Samarqandga borganman.", "I have been to Samarkand three times.", ["went"], ["I've been to Samarkand three times."]),
    s("Biz hali qaror qilmadik.", "We haven't decided yet.", ["didn't"]),
    s("Men uni kecha ko'rdim.", "I saw him yesterday.", ["seen"]),
    s("Men Londonda bo'lganman, lekin Parijda bo'lmaganman.", "I have been to London, but I haven't been to Paris.", ["was"]),
    s("Kamola hozirgina uyga keldi.", "Kamola has just come home.", ["came"], ["Kamola has just arrived home.", "Kamola has just got home."]),
  ],
  test: [
    s("Men Buxoroda bo'lganman.", "I have been to Bukhara.", ["was"], ["I've been to Bukhara."]),
    s("Jasur bu filmni ko'rgan.", "Jasur has seen this film.", ["saw"], ["Jasur has seen this movie."]),
    s("Biz yangi kompyuter sotib oldik.", "We have bought a new computer.", ["buyed"], ["We've bought a new computer."]),
    s("Men telefonimni yo'qotib qo'ydim.", "I have lost my phone.", ["losed"], ["I've lost my phone."]),
    s("Onam hozirgina ovqat pishirdi.", "My mother has just cooked dinner.", ["have"], [
      "My mom has just cooked dinner.",
      "My mum has just cooked dinner.",
      "My mother has just made dinner.",
      "My mom has just made dinner.",
      "My mum has just made dinner.",
    ]),
    s("Dars allaqachon boshlandi.", "The lesson has already started.", ["have"], ["The lesson has already begun.", "The class has already started."]),
    s("Men allaqachon uy vazifasini qilib bo'ldim.", "I have already done my homework.", ["did"], ["I've already done my homework.", "I have already finished my homework."]),
    s("Men hech qachon dengizni ko'rmaganman.", "I have never seen the sea.", ["saw"], ["I've never seen the sea."]),
    s("Sevara hech qachon Londonda bo'lmagan.", "Sevara has never been to London.", ["was"]),
    s("Men hali nonushta qilmadim.", "I haven't had breakfast yet.", ["hasn't"], ["I haven't eaten breakfast yet."]),
    s("Ali hali qo'ng'iroq qilmadi.", "Ali hasn't called yet.", ["haven't"], ["Ali hasn't phoned yet."]),
    s("Biz hali chipta sotib olmadik.", "We haven't bought the tickets yet.", ["didn't"], ["We haven't bought tickets yet."]),
    s("Siz hech samolyotda uchganmisiz?", "Have you ever flown on a plane?", ["flew"], ["Have you ever been on a plane?"]),
    s("Malika xatni yozib bo'ldimi?", "Has Malika written the letter?", ["wrote"]),
    s("Film tugadimi?", "Has the film finished?", ["have"], ["Has the movie finished?", "Has the film ended?", "Has the movie ended?"]),
    s("Sen hech Samarqandda bo'lganmisan? Ha.", "Have you ever been to Samarkand? Yes, I have.", ["was"]),
    s("Ular uyni sotishdimi? Yo'q, hali sotishmadi.", "Have they sold the house? No, they haven't.", ["sell"], ["Have they sold their house? No, they haven't."]),
    s("Men bu kitobni ikki marta o'qiganman.", "I have read this book twice.", ["readed"], ["I've read this book twice.", "I have read this book two times."]),
    s("Men uni o'tgan hafta ko'rdim.", "I saw her last week.", ["seen"]),
    s("Sardor hozirgina ishdan keldi.", "Sardor has just come from work.", ["came"], ["Sardor has just come home from work.", "Sardor has just got back from work."]),
  ],
};

/* ───────────────────────── 17. Plurals / Countables ───────────────────────── */

const PLURALS: GrammarTopicContent = {
  slug: "a1-plurals-countables",
  level: "A1",
  position: 17,
  title: { en: "Plurals, countable and uncountable", uz: "Ko'plik, sanaladigan va sanalmaydigan otlar" },
  explanation: {
    uz: [
      "Ko'plik odatda -s bilan: book - books. -s, -sh, -ch, -x, -o dan keyin -es: bus - buses, watch - watches, potato - potatoes.",
      "Undosh + y bo'lsa -ies: city - cities, baby - babies. -f / -fe ko'pincha -ves: knife - knives, leaf - leaves.",
      "Noto'g'ri ko'plik: man - men, woman - women, child - children, person - people, foot - feet, tooth - teeth, mouse - mice.",
      "Diqqat: o'zbek tilida \"uchta kitob\" (birlikda), ingliz tilida esa three books (ko'plikda)!",
      "Sanalmaydigan otlar (water, milk, money, bread, rice, information, advice, homework) ko'plik olmaydi va a / an bilan kelmaydi.",
      "How many + ko'plik (sanaladigan), How much + sanalmaydigan: How many apples? How much water?",
      "Sanalmaydiganni sanash: a glass of water, a piece of bread, a bottle of milk, a cup of tea.",
    ].join("\n"),
    pattern: "noun + s / es / ies / ves · irregular: men, women, children, people, feet, teeth · uncountable: no -s, no a / an · many + plural, much + uncountable",
    examples: [
      { en: "I have got three books.", uz: "Menda uchta kitob bor." },
      { en: "There are ten children in the room.", uz: "Xonada o'nta bola bor." },
      { en: "How much money have you got?", uz: "Qancha puling bor?" },
      { en: "Can I have a glass of water?", uz: "Bir stakan suv olsam bo'ladimi?" },
    ],
  },
  build: [
    s("Menda uchta kitob bor.", "I have got three books.", ["book"], ["I have three books.", "I've got three books."]),
    s("Xonada o'nta bola bor.", "There are ten children in the room.", ["childs"], ["There are ten kids in the room."]),
    s("Ikki ayol va bitta erkak kutyapti.", "Two women and a man are waiting.", ["womans"], ["Two women and one man are waiting."]),
    s("Bu shaharda ko'p odamlar yashaydi.", "Many people live in this city.", ["peoples"], ["A lot of people live in this city.", "Lots of people live in this city."]),
    s("Mening tishlarim og'riyapti.", "My teeth hurt.", ["tooths"]),
    s("Oyoqlarim sovuq.", "My feet are cold.", ["foots"]),
    s("Uyda ikkita sichqon bor.", "There are two mice in the house.", ["mouses"]),
    s("Avtobuslar har o'n daqiqada keladi.", "The buses come every ten minutes.", ["buss"], ["Buses come every ten minutes."]),
    s("Biz uchta shaharda bo'ldik.", "We visited three cities.", ["citys"], ["We have visited three cities.", "We have been to three cities."]),
    s("Stol ustida ikkita pichoq bor.", "There are two knives on the table.", ["knifes"]),
    s("Men ikki kilo kartoshka sotib oldim.", "I bought two kilos of potatoes.", ["potatos"], ["I bought two kilograms of potatoes."]),
    s("Malikaning ikkita chaqalog'i bor.", "Malika has got two babies.", ["babys"], ["Malika has two babies."]),
    s("Menga suv kerak.", "I need water.", ["a"], ["I need some water."]),
    s("Qancha puling bor?", "How much money have you got?", ["many"], ["How much money do you have?"]),
    s("Nechta olma sotib olding?", "How many apples did you buy?", ["much"]),
    s("Bir stakan suv olsam bo'ladimi?", "Can I have a glass of water?", ["waters"], ["Could I have a glass of water?"]),
    s("Iltimos, menga bir bo'lak non bering.", "Please give me a piece of bread.", ["breads"], ["Give me a piece of bread, please."]),
    s("Men har kuni ertalab bir piyola choy ichaman.", "I drink a cup of tea every morning.", ["teas"], ["Every morning I drink a cup of tea."]),
    s("Bizning ko'p uy vazifamiz bor.", "We have got a lot of homework.", ["homeworks"], ["We have a lot of homework.", "We've got a lot of homework.", "We have got lots of homework."]),
    s("U (yigit) menga yaxshi maslahat berdi.", "He gave me good advice.", ["advices"], ["He gave me some good advice.", "He gave me a piece of good advice."]),
    s("Shishada sut yo'q.", "There isn't any milk in the bottle.", ["milks"], ["There is no milk in the bottle."]),
    s("Muzlatgichda ko'p tuxum yo'q.", "There aren't many eggs in the fridge.", ["much"]),
    s("Bizda ko'p vaqt yo'q.", "We haven't got much time.", ["many"], ["We don't have much time."]),
    s("Sinfda nechta o'quvchi bor?", "How many students are there in the class?", ["much"], ["How many pupils are there in the class?"]),
    s("Bir shisha sut sotib ol.", "Buy a bottle of milk.", ["milks"], ["Buy a bottle of milk, please.", "Please buy a bottle of milk."]),
    s("Men bu ma'lumotni internetdan topdim.", "I found this information on the internet.", ["informations"], ["I found this information online."]),
    s("Bu odamlar mening do'stlarim.", "These people are my friends.", ["this"]),
    s("Erkaklar futbol o'ynayapti, ayollar esa gaplashyapti.", "The men are playing football and the women are talking.", ["mans"], [
      "The men are playing football, and the women are talking.",
      "The men are playing soccer and the women are talking.",
    ]),
    s("Kuzda barglar sariq bo'ladi.", "Leaves are yellow in autumn.", ["leafs"], ["Leaves turn yellow in autumn.", "In autumn leaves are yellow.", "In autumn leaves turn yellow."]),
    s("Guruchga qancha pul to'lading?", "How much did you pay for the rice?", ["many"]),
  ],
  test: [
    s("Menda beshta qalam bor.", "I have got five pencils.", ["pencil"], ["I have five pencils.", "I've got five pencils.", "I have got five pens.", "I have five pens."]),
    s("Parkda ko'p bolalar bor.", "There are many children in the park.", ["childs"], [
      "There are a lot of children in the park.",
      "There are lots of children in the park.",
      "There are many kids in the park.",
      "There are a lot of kids in the park.",
    ]),
    s("Uch erkak eshik oldida turibdi.", "Three men are standing at the door.", ["mans"], ["Three men are standing in front of the door."]),
    s("Bu ayollar o'qituvchilar.", "These women are teachers.", ["womans"]),
    s("Chaqaloqning ikkita tishi bor.", "The baby has got two teeth.", ["tooths"], ["The baby has two teeth."]),
    s("Mening oyoqlarim charchadi.", "My feet are tired.", ["foots"]),
    s("Biz ko'p mamlakatlarda bo'lganmiz.", "We have been to many countries.", ["countrys"], ["We've been to many countries.", "We have been to a lot of countries."]),
    s("U (qiz) uchta soat sotib oldi.", "She bought three watches.", ["watchs"]),
    s("Menga choy kerak.", "I need tea.", ["a"], ["I need some tea."]),
    s("Qancha suv ichasan?", "How much water do you drink?", ["many"]),
    s("Nechta akang bor?", "How many brothers have you got?", ["much"], ["How many brothers do you have?"]),
    s("Bir piyola qahva olsam bo'ladimi?", "Can I have a cup of coffee?", ["coffees"], ["Could I have a cup of coffee?"]),
    s("Bir bo'lak tort xohlaysanmi?", "Do you want a piece of cake?", ["cakes"], ["Would you like a piece of cake?"]),
    s("Bugun uy vazifam ko'p emas.", "I haven't got much homework today.", ["many"], ["I don't have much homework today.", "Today I haven't got much homework."]),
    s("Bizda ko'p pul yo'q.", "We haven't got much money.", ["many"], ["We don't have much money."]),
    s("Sumkada ko'p kitoblar yo'q.", "There aren't many books in the bag.", ["much"]),
    s("O'qituvchi bizga foydali ma'lumot berdi.", "The teacher gave us useful information.", ["informations"], ["The teacher gave us some useful information."]),
    s("Bir shisha suv sotib oldim.", "I bought a bottle of water.", ["waters"]),
    s("Bu odamlar qayerdan?", "Where are these people from?", ["peoples"]),
    s("Uyda nechta xona bor?", "How many rooms are there in the house?", ["much"]),
  ],
};

/* ───────────────────────────── 18. Some / any ───────────────────────────── */

const SOME_ANY: GrammarTopicContent = {
  slug: "a1-some-any",
  level: "A1",
  position: 18,
  title: { en: "Some / any", uz: "Some / any (biroz, bir nechta)" },
  explanation: {
    uz: [
      "Some va any - \"biroz, bir nechta\" ma'nosida: ko'plik (some apples) va sanalmaydigan otlar (some water) bilan.",
      "Darak gapda some: I have got some friends in London. There is some milk.",
      "Inkor gapda any: I haven't got any money. There aren't any eggs.",
      "So'roq gapda any: Have you got any questions? Is there any sugar?",
      "Taklif va iltimosda some: Would you like some tea? Can I have some water?",
      "Shuningdek: something / anything, somebody / anybody, somewhere / anywhere - xuddi shu qoida bilan.",
    ].join("\n"),
    pattern: "+ some · - not … any · ? any …? · offer / request: Would you like some …? / Can I have some …?",
    examples: [
      { en: "There are some apples in the bag.", uz: "Sumkada bir nechta olma bor." },
      { en: "I haven't got any money.", uz: "Menda umuman pul yo'q." },
      { en: "Have you got any questions?", uz: "Savollaringiz bormi?" },
      { en: "Would you like some tea?", uz: "Choy ichasizmi?" },
    ],
  },
  build: [
    s("Sumkada bir nechta olma bor.", "There are some apples in the bag.", ["any"]),
    s("Muzlatgichda biroz sut bor.", "There is some milk in the fridge.", ["any"]),
    s("Londonda bir nechta do'stlarim bor.", "I have got some friends in London.", ["any"], ["I have some friends in London.", "I've got some friends in London."]),
    s("Men biroz non sotib oldim.", "I bought some bread.", ["any"]),
    s("Bizga biroz shakar kerak.", "We need some sugar.", ["any"]),
    s("Menda umuman pul yo'q.", "I haven't got any money.", ["some"], ["I don't have any money."]),
    s("Muzlatgichda tuxum yo'q.", "There aren't any eggs in the fridge.", ["some"]),
    s("Choynakda choy qolmadi.", "There isn't any tea in the teapot.", ["some"]),
    s("Biz hech qanday savol bermadik.", "We didn't ask any questions.", ["some"]),
    s("Ali hech qanday sport bilan shug'ullanmaydi.", "Ali doesn't do any sport.", ["some"], ["Ali doesn't do any sports."]),
    s("Savollaringiz bormi?", "Have you got any questions?", ["some"], ["Do you have any questions?"]),
    s("Shakar bormi?", "Is there any sugar?", ["some"]),
    s("Sinfda o'quvchilar bormi?", "Are there any students in the classroom?", ["some"], ["Are there any pupils in the classroom?"]),
    s("Sizda bolalar bormi?", "Have you got any children?", ["some"], ["Do you have any children?", "Have you got any kids?", "Do you have any kids?"]),
    s("Choy ichasizmi?", "Would you like some tea?", ["any"]),
    s("Biroz suv olsam bo'ladimi?", "Can I have some water?", ["any"], ["Could I have some water?"]),
    s("Biroz tort xohlaysanmi?", "Would you like some cake?", ["any"]),
    s("Kimdir eshikni taqillatyapti.", "Somebody is knocking at the door.", ["anybody"], [
      "Someone is knocking at the door.",
      "Somebody is knocking on the door.",
      "Someone is knocking on the door.",
    ]),
    s("Men hech narsani ko'rmayapman.", "I can't see anything.", ["something"]),
    s("Men biror narsa yemoqchiman.", "I want to eat something.", ["anything"]),
    s("Bu yerda hech kim yo'q.", "There isn't anybody here.", ["somebody"], ["There isn't anyone here."]),
    s("Sizga biror narsa kerakmi?", "Do you need anything?", ["something"]),
    s("Men kalitlarimni hech qayerdan topa olmayapman.", "I can't find my keys anywhere.", ["somewhere"]),
    s("Biz ta'tilda biror joyga bormoqchimiz.", "We want to go somewhere on holiday.", ["anywhere"], ["We want to go somewhere on vacation."]),
    s("Ota-onam biroz meva sotib olishdi.", "My parents bought some fruit.", ["any"]),
    s("Bugun uy vazifasi yo'q.", "There isn't any homework today.", ["some"], ["Today there isn't any homework."]),
    s("Shkafda ko'ylaklar bormi?", "Are there any shirts in the wardrobe?", ["some"]),
    s("Menda biroz vaqt bor, lekin pul yo'q.", "I have got some time, but I haven't got any money.", ["many"], [
      "I have some time, but I don't have any money.",
    ]),
    s("Kechagi ziyofatda qiziq odamlar bor edi.", "There were some interesting people at the party.", ["any"]),
    s("Bu yerda biror do'kon bormi?", "Are there any shops here?", ["some"], ["Are there any shops near here?", "Are there any stores here?"]),
  ],
  test: [
    s("Stol ustida bir nechta kitob bor.", "There are some books on the table.", ["any"], ["There are some books on the desk."]),
    s("Stakanda biroz suv bor.", "There is some water in the glass.", ["any"]),
    s("Men biroz guruch sotib oldim.", "I bought some rice.", ["any"]),
    s("Bizga biroz tuxum kerak.", "We need some eggs.", ["any"]),
    s("Madinaning Samarqandda qarindoshlari bor.", "Madina has got some relatives in Samarkand.", ["any"], ["Madina has some relatives in Samarkand."]),
    s("Menda umuman vaqt yo'q.", "I haven't got any time.", ["some"], ["I don't have any time."]),
    s("Ko'chada mashinalar yo'q.", "There aren't any cars in the street.", ["some"], ["There aren't any cars on the street."]),
    s("Muzlatgichda go'sht yo'q.", "There isn't any meat in the fridge.", ["some"]),
    s("Sardor hech qanday kitob o'qimaydi.", "Sardor doesn't read any books.", ["some"]),
    s("Sut bormi?", "Is there any milk?", ["some"]),
    s("Sizda opa-singillar bormi?", "Have you got any sisters?", ["some"], ["Do you have any sisters?"]),
    s("Bu yerda kafelar bormi?", "Are there any cafes here?", ["some"], ["Are there any cafes near here?"]),
    s("Qahva ichasizmi?", "Would you like some coffee?", ["any"]),
    s("Biroz non olsam bo'ladimi?", "Can I have some bread?", ["any"], ["Could I have some bread?"]),
    s("Kimdir sizga qo'ng'iroq qildi.", "Somebody called you.", ["anybody"], ["Someone called you.", "Somebody phoned you.", "Someone phoned you."]),
    s("Men hech narsani eshitmayapman.", "I can't hear anything.", ["something"]),
    s("Men senga biror narsa aytmoqchiman.", "I want to tell you something.", ["anything"]),
    s("Uyda hech kim yo'q.", "There isn't anybody at home.", ["somebody"], ["There isn't anyone at home."]),
    s("Bugun sizga biror narsa kerakmi?", "Do you need anything today?", ["something"]),
    s("Biroz meva xohlaysanmi?", "Would you like some fruit?", ["any"]),
  ],
};

/* ───────────────────────────── 19. Articles ───────────────────────────── */

const ARTICLES: GrammarTopicContent = {
  slug: "a1-articles",
  level: "A1",
  position: 19,
  title: { en: "Articles: a / an / the", uz: "Artikllar: a / an / the" },
  explanation: {
    uz: [
      "A / an - \"bitta, qandaydir\": birlikdagi sanaladigan ot bilan, birinchi marta tilga olinganda: I have got a dog.",
      "An undosh emas, unli TOVUSH oldidan: an apple, an orange, an hour (h o'qilmaydi). Lekin a university (yu tovushi).",
      "The - \"o'sha, ma'lum\": ikkala tomon ham qaysi ekanini bilganda yoki ikkinchi marta: I have got a dog. The dog is black.",
      "Yagona narsalar bilan the: the sun, the moon, the sky, the internet.",
      "Kasb bilan a / an: She is a doctor. He is an engineer.",
      "Artikl kerak emas: umumiy ko'plik va sanalmaydigan otlar (I like cats. Water is important), ismlar, shaharlar, tillar, sport, ovqatlanish (have breakfast), at home, go to school / bed / work.",
    ].join("\n"),
    pattern: "a + consonant sound · an + vowel sound · the + something specific / unique · no article: general plurals, uncountables, names, meals, sports",
    examples: [
      { en: "I have got a cat and a dog.", uz: "Mening mushugim va itim bor." },
      { en: "She is an English teacher.", uz: "U ingliz tili o'qituvchisi." },
      { en: "The sun is very hot today.", uz: "Bugun quyosh juda issiq." },
      { en: "I like apples.", uz: "Men olmani yaxshi ko'raman." },
    ],
  },
  build: [
    s("Mening itim bor.", "I have got a dog.", ["an"], ["I have a dog.", "I've got a dog."]),
    s("Men olma yedim.", "I ate an apple.", ["a"], ["I have eaten an apple."]),
    s("U (qiz) shifokor.", "She is a doctor.", ["an"]),
    s("Akam muhandis.", "My brother is an engineer.", ["a"], ["My older brother is an engineer."]),
    s("Bu juda qiziq kitob.", "This is a very interesting book.", ["an"]),
    s("Bu qiziq kitob.", "This is an interesting book.", ["a"]),
    s("Men bir soat kutdim.", "I waited for an hour.", ["a"], ["I waited an hour.", "I waited for one hour."]),
    s("Ali universitetda o'qiydi.", "Ali studies at a university.", ["an"], ["Ali studies at university."]),
    s("Mening mushugim bor. Mushuk qora.", "I have got a cat. The cat is black.", ["an"], ["I have a cat. The cat is black.", "I've got a cat. The cat is black."]),
    s("Quyosh juda issiq.", "The sun is very hot.", ["a"]),
    s("Bugun osmon ko'k.", "The sky is blue today.", ["a"], ["Today the sky is blue."]),
    s("Iltimos, eshikni yop.", "Please close the door.", ["a"], ["Close the door, please.", "Please shut the door.", "Shut the door, please."]),
    s("Kalitlar stol ustida.", "The keys are on the table.", ["a"]),
    s("Men mushuklarni yaxshi ko'raman.", "I like cats.", ["the"], ["I love cats."]),
    s("Suv hayot uchun muhim.", "Water is important for life.", ["the"]),
    s("Madina Toshkentda yashaydi.", "Madina lives in Tashkent.", ["the"]),
    s("Biz ingliz tilini o'rganyapmiz.", "We are learning English.", ["the"], ["We are studying English."]),
    s("Ular futbol o'ynashyapti.", "They are playing football.", ["the"], ["They are playing soccer."]),
    s("Men soat yettida nonushta qilaman.", "I have breakfast at seven o'clock.", ["the"], ["I have breakfast at seven.", "I eat breakfast at seven o'clock.", "I eat breakfast at seven."]),
    s("Bolalar maktabda.", "The children are at school.", ["a"], ["The kids are at school."]),
    s("Men har kuni ishga boraman.", "I go to work every day.", ["the"]),
    s("Men har kuni soat o'nda uxlagani yotaman.", "I go to bed at ten o'clock every day.", ["the"], ["I go to bed at ten every day."]),
    s("Otam uyda.", "My father is at home.", ["the"], ["My dad is at home."]),
    s("Sumkamda olma va banan bor.", "There is an apple and a banana in my bag.", ["the"], ["There is a banana and an apple in my bag."]),
    s("Bu yerga yaqin bank bormi?", "Is there a bank near here?", ["an"]),
    s("Men gitara chalaman.", "I play the guitar.", ["a"], ["I play guitar."]),
    s("Men internetda film ko'rdim.", "I watched a film on the internet.", ["an"], ["I watched a movie on the internet.", "I watched a film online.", "I watched a movie online."]),
    s("Oy bugun juda chiroyli.", "The moon is very beautiful tonight.", ["a"], ["The moon is very beautiful today."]),
    s("Malika apelsin va nok sotib oldi.", "Malika bought an orange and a pear.", ["the"], ["Malika bought a pear and an orange."]),
    s("U (yigit) halol odam.", "He is an honest man.", ["a"], ["He is an honest person."]),
  ],
  test: [
    s("Mening velosipedim bor.", "I have got a bike.", ["an"], ["I have a bike.", "I've got a bike.", "I have got a bicycle.", "I have a bicycle."]),
    s("Men tuxum yedim.", "I ate an egg.", ["a"], ["I have eaten an egg."]),
    s("Otam haydovchi.", "My father is a driver.", ["an"], ["My dad is a driver."]),
    s("Opam rassom.", "My sister is an artist.", ["a"], ["My older sister is an artist."]),
    s("Bu juda eski uy.", "This is a very old house.", ["an"]),
    s("Bu eski uy.", "This is an old house.", ["a"]),
    s("Men yarim soat kutdim.", "I waited for half an hour.", ["a"], ["I waited half an hour."]),
    s("Mening itim bor. It oq.", "I have got a dog. The dog is white.", ["an"], ["I have a dog. The dog is white.", "I've got a dog. The dog is white."]),
    s("Quyosh chiqyapti.", "The sun is rising.", ["a"], ["The sun is coming up."]),
    s("Iltimos, derazani och.", "Please open the window.", ["a"], ["Open the window, please."]),
    s("Men itlarni yaxshi ko'raman.", "I like dogs.", ["the"], ["I love dogs."]),
    s("Sut sog'liq uchun foydali.", "Milk is good for your health.", ["the"], ["Milk is good for health.", "Milk is healthy."]),
    s("Sardor Samarqandda ishlaydi.", "Sardor works in Samarkand.", ["the"]),
    s("Ular basketbol o'ynashyapti.", "They are playing basketball.", ["the"]),
    s("Biz soat birda tushlik qilamiz.", "We have lunch at one o'clock.", ["the"], ["We have lunch at one.", "We eat lunch at one o'clock.", "We eat lunch at one."]),
    s("Ukam maktabda.", "My brother is at school.", ["the"], ["My little brother is at school.", "My younger brother is at school."]),
    s("Bu yerga yaqin dorixona bormi?", "Is there a pharmacy near here?", ["an"]),
    s("Men pianino chalaman.", "I play the piano.", ["a"], ["I play piano."]),
    s("Zarina olma va limon sotib oldi.", "Zarina bought an apple and a lemon.", ["the"], ["Zarina bought a lemon and an apple."]),
    s("Men har kuni avtobusda ishga boraman.", "I go to work by bus every day.", ["the"], ["Every day I go to work by bus."]),
  ],
};

/* ───────────────────────── 20. Adjectives / Adverbs ───────────────────────── */

const ADJ_ADV: GrammarTopicContent = {
  slug: "a1-adjectives-adverbs",
  level: "A1",
  position: 20,
  title: { en: "Adjectives and adverbs", uz: "Sifat va ravish (quick / quickly)" },
  explanation: {
    uz: [
      "Sifat (adjective) otni tasvirlaydi: a fast car, a careful driver. Sifat otdan OLDIN keladi: a red car (car red emas).",
      "Sifat to be, look, feel dan keyin ham keladi: She is happy. You look tired.",
      "Sifat ko'plik olmaydi: big houses (bigs houses emas).",
      "Ravish (adverb) fe'lni tasvirlaydi - ish QANDAY qilinadi: He drives carefully. She speaks slowly.",
      "Ko'pincha sifat + -ly: quick - quickly, slow - slowly, careful - carefully, easy - easily, happy - happily.",
      "Noto'g'ri: good - well, fast - fast, hard - hard, late - late. He is a good player = He plays well.",
    ].join("\n"),
    pattern: "adjective + noun · be / look / feel + adjective · verb (+ object) + adverb · adjective + ly · good → well, fast → fast, hard → hard",
    examples: [
      { en: "Ali is a careful driver.", uz: "Ali ehtiyotkor haydovchi." },
      { en: "Ali drives carefully.", uz: "Ali ehtiyotkorlik bilan haydaydi." },
      { en: "She speaks English well.", uz: "U ingliz tilida yaxshi gapiradi." },
      { en: "You look tired.", uz: "Charchagan ko'rinasan." },
    ],
  },
  build: [
    s("Bu qizil mashina.", "This is a red car.", ["reds"]),
    s("Ali ehtiyotkor haydovchi.", "Ali is a careful driver.", ["carefully"]),
    s("Ali ehtiyotkorlik bilan haydaydi.", "Ali drives carefully.", ["careful"]),
    s("U (qiz) sekin gapiradi.", "She speaks slowly.", ["slow"]),
    s("Bu sekin kompyuter.", "This is a slow computer.", ["slowly"]),
    s("Madina ingliz tilida yaxshi gapiradi.", "Madina speaks English well.", ["good"]),
    s("Madina yaxshi o'qituvchi.", "Madina is a good teacher.", ["well"]),
    s("Sardor tez yuguradi.", "Sardor runs fast.", ["fastly"], ["Sardor runs quickly."]),
    s("Biz ko'p ishlaymiz.", "We work hard.", ["hardly"]),
    s("Bular katta uylar.", "These are big houses.", ["bigs"]),
    s("Charchagan ko'rinasan.", "You look tired.", ["tiredly"]),
    s("Men o'zimni baxtli his qilyapman.", "I feel happy.", ["happily"]),
    s("Bolalar baxtiyor o'ynashyapti.", "The children are playing happily.", ["happy"], ["The kids are playing happily."]),
    s("Bu savol oson.", "This question is easy.", ["easily"]),
    s("Men bu savolga oson javob berdim.", "I answered the question easily.", ["easy"], ["I answered this question easily."]),
    s("Iltimos, sekinroq gapiring.", "Please speak slowly.", ["slow"], ["Speak slowly, please."]),
    s("U (yigit) baland ovozda gapiradi.", "He speaks loudly.", ["loud"], ["He talks loudly."]),
    s("Musiqa juda baland.", "The music is very loud.", ["loudly"]),
    s("Zarina chiroyli qo'shiq aytadi.", "Zarina sings beautifully.", ["beautiful"]),
    s("Zarina chiroyli qiz.", "Zarina is a beautiful girl.", ["beautifully"]),
    s("Ular jim o'tirishibdi.", "They are sitting quietly.", ["quiet"]),
    s("Kutubxona juda jim.", "The library is very quiet.", ["quietly"]),
    s("Men har kuni kech turaman.", "I get up late every day.", ["lately"], ["I wake up late every day."]),
    s("Avtobus tez haydaydi.", "The bus goes fast.", ["fastly"], ["The bus goes quickly."]),
    s("Bu juda tez poyezd.", "This is a very fast train.", ["fastly"]),
    s("Iltimos, eshikni ehtiyotlik bilan yoping.", "Please close the door carefully.", ["careful"], ["Close the door carefully, please."]),
    s("Malika uy vazifasini tez qildi.", "Malika did her homework quickly.", ["quick"]),
    s("Bu oson imtihon edi.", "It was an easy exam.", ["easily"]),
    s("Akam futbolni yaxshi o'ynaydi.", "My brother plays football well.", ["good"], ["My brother plays soccer well."]),
    s("Uning (yigitning) ingliz tili juda yaxshi.", "His English is very good.", ["well"]),
  ],
  test: [
    s("Bu ko'k ko'ylak.", "This is a blue shirt.", ["blues"], ["This is a blue dress."]),
    s("Otam ehtiyotkor odam.", "My father is a careful man.", ["carefully"], ["My dad is a careful man.", "My father is a careful person.", "My dad is a careful person."]),
    s("Otam ehtiyotkorlik bilan haydaydi.", "My father drives carefully.", ["careful"], ["My dad drives carefully."]),
    s("Kamola tez gapiradi.", "Kamola speaks quickly.", ["quick"], ["Kamola speaks fast.", "Kamola talks quickly.", "Kamola talks fast."]),
    s("Jasur rus tilida yaxshi gapiradi.", "Jasur speaks Russian well.", ["good"]),
    s("Jasur yaxshi talaba.", "Jasur is a good student.", ["well"]),
    s("Ot tez yuguradi.", "The horse runs fast.", ["fastly"], ["The horse runs quickly.", "Horses run fast."]),
    s("Ular qattiq ishlaydi.", "They work hard.", ["hardly"]),
    s("Bular yangi kitoblar.", "These are new books.", ["news"]),
    s("Sen baxtli ko'rinasan.", "You look happy.", ["happily"]),
    s("Men o'zimni yomon his qilyapman.", "I feel bad.", ["badly"]),
    s("Bu mashq juda oson.", "This exercise is very easy.", ["easily"]),
    s("Biz testni oson yozdik.", "We did the test easily.", ["easy"], ["We passed the test easily.", "We wrote the test easily."]),
    s("Iltimos, jim bo'ling.", "Please be quiet.", ["quietly"], ["Be quiet, please."]),
    s("Chaqaloq tinch uxlayapti.", "The baby is sleeping quietly.", ["quiet"], ["The baby is sleeping peacefully."]),
    s("Sevara chiroyli raqsga tushadi.", "Sevara dances beautifully.", ["beautiful"]),
    s("Bugun men kech keldim.", "I came late today.", ["lately"], ["Today I came late.", "I arrived late today."]),
    s("Bu juda qimmat telefon.", "This is a very expensive phone.", ["expensively"]),
    s("Timur imtihonga yaxshi tayyorlandi.", "Timur prepared well for the exam.", ["good"], ["Timur prepared for the exam well."]),
    s("Bu sekin avtobus.", "This is a slow bus.", ["slowly"]),
  ],
};

/* ───────────────────────── 21. Adjective degrees ───────────────────────── */

const DEGREES: GrammarTopicContent = {
  slug: "a1-adjective-degrees",
  level: "A1",
  position: 21,
  title: { en: "Comparatives and superlatives", uz: "Sifat darajalari (bigger, the biggest)" },
  explanation: {
    uz: [
      "Qiyosiy daraja (-roq): qisqa sifat + -er + than: Ali is taller than Sardor = Ali Sardordan balandroq.",
      "Orttirma daraja (eng): the + sifat + -est: Ali is the tallest in the class = Ali sinfdagi eng baland.",
      "Imlo: big - bigger - the biggest, hot - hotter, nice - nicer, easy - easier - the easiest, happy - happier.",
      "Uzun sifatlar (2-3 bo'g'in) bilan more / the most: more interesting, the most beautiful.",
      "Noto'g'ri: good - better - the best, bad - worse - the worst, far - further - the furthest.",
      "Bir xillik: as + sifat + as: Madina is as tall as Malika. Inkor: not as … as.",
      "Diqqat: more bigger yoki the most best demaymiz!",
    ].join("\n"),
    pattern: "adjective-er + than · more + long adjective + than · the + adjective-est · the most + long adjective · good → better → the best · bad → worse → the worst · as … as",
    examples: [
      { en: "Ali is taller than Sardor.", uz: "Ali Sardordan balandroq." },
      { en: "This is the biggest city in Uzbekistan.", uz: "Bu O'zbekistondagi eng katta shahar." },
      { en: "English is more interesting than maths.", uz: "Ingliz tili matematikadan qiziqroq." },
      { en: "Madina is as tall as Malika.", uz: "Madina Malika bilan bir xil bo'yda." },
    ],
  },
  build: [
    s("Ali Sardordan balandroq.", "Ali is taller than Sardor.", ["then"]),
    s("Mening uyim seningkidan kattaroq.", "My house is bigger than yours.", ["biger"], ["My house is bigger than your house."]),
    s("Bugun kechagidan issiqroq.", "Today is hotter than yesterday.", ["more"], ["It is hotter today than yesterday."]),
    s("Bu savol o'sha savoldan osonroq.", "This question is easier than that one.", ["easyer"], ["This question is easier than that question."]),
    s("Poyezd avtobusdan tezroq.", "The train is faster than the bus.", ["more"], ["A train is faster than a bus.", "Trains are faster than buses."]),
    s("Ingliz tili matematikadan qiziqroq.", "English is more interesting than maths.", ["interestinger"], ["English is more interesting than math.", "English is more interesting than mathematics."]),
    s("Bu ko'ylak u ko'ylakdan qimmatroq.", "This dress is more expensive than that one.", ["expensiver"], ["This dress is more expensive than that dress."]),
    s("Sening telefoning menikidan yaxshiroq.", "Your phone is better than mine.", ["gooder"], ["Your phone is better than my phone."]),
    s("Bugun havo kechagidan yomonroq.", "The weather is worse today than yesterday.", ["badder"], ["Today the weather is worse than yesterday."]),
    s("Malika singlisidan baxtliroq.", "Malika is happier than her sister.", ["happyer"]),
    s("Ali sinfdagi eng baland bola.", "Ali is the tallest boy in the class.", ["taller"], ["Ali is the tallest boy in our class."]),
    s("Toshkent O'zbekistondagi eng katta shahar.", "Tashkent is the biggest city in Uzbekistan.", ["most"], ["Tashkent is the largest city in Uzbekistan."]),
    s("Bu yilning eng sovuq kuni.", "This is the coldest day of the year.", ["colder"]),
    s("Bu eng oson mashq.", "This is the easiest exercise.", ["easyest"]),
    s("Bu do'kondagi eng qimmat soat.", "This is the most expensive watch in the shop.", ["expensivest"], ["This is the most expensive watch in the store."]),
    s("Bu men ko'rgan eng qiziq film.", "This is the most interesting film I have seen.", ["more"], [
      "This is the most interesting movie I have seen.",
      "This is the most interesting film I've seen.",
      "This is the most interesting movie I've seen.",
    ]),
    s("Madina sinfdagi eng yaxshi o'quvchi.", "Madina is the best student in the class.", ["goodest"], ["Madina is the best pupil in the class.", "Madina is the best student in our class."]),
    s("Bu eng yomon restoran.", "This is the worst restaurant.", ["baddest"]),
    s("Samarqand eng chiroyli shahar.", "Samarkand is the most beautiful city.", ["beautifullest"]),
    s("Madina Malika bilan bir xil bo'yda.", "Madina is as tall as Malika.", ["than"]),
    s("Mening xonam seningki kabi katta emas.", "My room isn't as big as yours.", ["than"], ["My room isn't as big as your room."]),
    s("Avtobus poyezd kabi tez emas.", "The bus isn't as fast as the train.", ["than"], ["A bus isn't as fast as a train.", "Buses aren't as fast as trains."]),
    s("Akam mendan katta.", "My brother is older than me.", ["then"], ["My brother is older than I am.", "My brother is older than I."]),
    s("Qishda kunlar qisqaroq.", "Days are shorter in winter.", ["more"], ["The days are shorter in winter.", "In winter days are shorter.", "In winter the days are shorter."]),
    s("Bu kitob u kitobdan qalinroq.", "This book is thicker than that one.", ["more"], ["This book is thicker than that book."]),
    s("Sen mendan yaxshiroq gapirasan.", "You speak better than me.", ["gooder"], ["You speak better than I do.", "You speak better than I."]),
    s("Oilamizdagi eng yosh kishi kim?", "Who is the youngest in our family?", ["younger"], ["Who is the youngest person in our family?"]),
    s("Bu dunyodagi eng uzun daryo.", "This is the longest river in the world.", ["longer"]),
    s("Men ingliz tilini rus tilidan qiyinroq deb o'ylayman.", "I think English is more difficult than Russian.", ["difficulter"], ["I think English is harder than Russian."]),
    s("Bugun hayotimdagi eng yaxshi kun edi.", "Today was the best day of my life.", ["better"]),
  ],
  test: [
    s("Jasur Timurdan balandroq.", "Jasur is taller than Timur.", ["then"]),
    s("Mening sumkam seningkidan kattaroq.", "My bag is bigger than yours.", ["biger"], ["My bag is bigger than your bag."]),
    s("Yozda havo bahordan issiqroq.", "Summer is hotter than spring.", ["more"], ["It is hotter in summer than in spring."]),
    s("Bu mashq kechagisidan osonroq.", "This exercise is easier than yesterday's.", ["easyer"], ["This exercise is easier than the one yesterday."]),
    s("Samolyot poyezddan tezroq.", "A plane is faster than a train.", ["more"], ["The plane is faster than the train.", "Planes are faster than trains."]),
    s("Bu kitob u kitobdan qiziqroq.", "This book is more interesting than that one.", ["interestinger"], ["This book is more interesting than that book."]),
    s("Mening ingliz tilim seningkidan yomonroq.", "My English is worse than yours.", ["badder"]),
    s("Bu kafe u kafedan yaxshiroq.", "This cafe is better than that one.", ["gooder"], ["This cafe is better than that cafe."]),
    s("Kamola onasidan yoshroq ko'rinadi.", "Kamola looks younger than her mother.", ["more"], ["Kamola looks younger than her mom.", "Kamola looks younger than her mum."]),
    s("Sevara sinfdagi eng baland qiz.", "Sevara is the tallest girl in the class.", ["taller"], ["Sevara is the tallest girl in our class."]),
    s("Bu shahardagi eng katta park.", "This is the biggest park in the city.", ["most"], ["This is the largest park in the city.", "This is the biggest park in the town."]),
    s("Bu eng arzon telefon.", "This is the cheapest phone.", ["cheaper"]),
    s("Bu eng qiyin savol.", "This is the most difficult question.", ["difficultest"], ["This is the hardest question."]),
    s("Sardor jamoadagi eng yaxshi o'yinchi.", "Sardor is the best player in the team.", ["goodest"], ["Sardor is the best player on the team."]),
    s("Bu hayotimdagi eng yomon kun.", "This is the worst day of my life.", ["baddest"]),
    s("Zarina Kamola bilan bir xil yoshda.", "Zarina is as old as Kamola.", ["than"]),
    s("Bu film kitob kabi yaxshi emas.", "This film isn't as good as the book.", ["than"], ["This movie isn't as good as the book."]),
    s("Singlim mendan kichik.", "My sister is younger than me.", ["then"], ["My sister is younger than I am.", "My sister is younger than I."]),
    s("O'zbekistondagi eng chiroyli shahar qaysi?", "What is the most beautiful city in Uzbekistan?", ["beautifullest"], ["Which is the most beautiful city in Uzbekistan?"]),
    s("Choy qahvadan arzonroq.", "Tea is cheaper than coffee.", ["more"]),
  ],
};

export const A1_PART4_TOPICS: GrammarTopicContent[] = [PRESENT_PERFECT, PLURALS, SOME_ANY, ARTICLES, ADJ_ADV, DEGREES];
