/**
 * A1 (Beginner) grammar — topics 10-15: To-infinitive / Gerund, Past Simple,
 * Prepositions, Future Simple, Question words, Linkers.
 * Written by Claude as a DRAFT for teacher review (imported unpublished).
 * APPEND-ONLY: never reorder or delete items once shipped — progress keys on
 * (topic slug, kind, position). Validated by tests/grammar-content.test.ts.
 */
import type { GrammarItemContent, GrammarTopicContent } from "@shared/grammar/types";

/** One sentence: Uzbek prompt, model English, traps, and other correct answers. */
const s = (uz: string, en: string, traps: string[], alt?: string[]): GrammarItemContent =>
  alt ? { uz, en, traps, alt } : { uz, en, traps };

/* ───────────────────────── 10. To-infinitive / Gerund ───────────────────────── */

const INFINITIVE_GERUND: GrammarTopicContent = {
  slug: "a1-infinitive-gerund",
  level: "A1",
  position: 10,
  title: { en: "To + verb / verb + -ing", uz: "To + fe'l / fe'l + -ing" },
  explanation: {
    uz: [
      "Ba'zi fe'llardan keyin to + fe'l keladi: want, would like, need, hope, decide, plan, learn.",
      "I want to travel = Men sayohat qilishni xohlayman. She needs to study.",
      "Ba'zi fe'llardan keyin fe'l + -ing keladi: enjoy, finish, stop, hate, don't mind, be good at.",
      "I enjoy reading = Men kitob o'qishni yoqtiraman. He finished working.",
      "Like, love, hate dan keyin ikkalasi ham bo'ladi: I like swimming = I like to swim.",
      "Predlogdan keyin doim -ing: good at drawing, interested in learning, before going.",
    ].join("\n"),
    pattern: "want / would like / need / hope / decide + to + verb · enjoy / finish / stop / be good at + verb-ing · like / love / hate + to verb or verb-ing",
    examples: [
      { en: "I want to learn English.", uz: "Men ingliz tilini o'rganmoqchiman." },
      { en: "Madina enjoys cooking.", uz: "Madina ovqat pishirishni yoqtiradi." },
      { en: "We decided to stay at home.", uz: "Biz uyda qolishga qaror qildik." },
      { en: "He is good at drawing.", uz: "U rasm chizishni yaxshi biladi." },
    ],
  },
  build: [
    s("Men ingliz tilini o'rganmoqchiman.", "I want to learn English.", ["learning"], ["I want to study English."]),
    s("Ali shifokor bo'lishni xohlaydi.", "Ali wants to be a doctor.", ["being"], ["Ali wants to become a doctor."]),
    s("Biz yangi mashina sotib olishimiz kerak.", "We need to buy a new car.", ["buying"]),
    s("Men bir piyola choy ichmoqchi edim.", "I would like to drink a cup of tea.", ["drinking"], ["I'd like to drink a cup of tea."]),
    s("Malika Londonga borishni rejalashtiryapti.", "Malika is planning to go to London.", ["going"], ["Malika plans to go to London."]),
    s("Ular uyda qolishga qaror qilishdi.", "They decided to stay at home.", ["staying"]),
    s("Men seni tez orada ko'rishga umid qilaman.", "I hope to see you soon.", ["seeing"]),
    s("Ukam suzishni o'rganyapti.", "My brother is learning to swim.", ["swimming"], ["My little brother is learning to swim.", "My younger brother is learning to swim."]),
    s("Men kitob o'qishni yoqtiraman.", "I enjoy reading books.", ["to"], ["I like reading books.", "I like to read books.", "I love reading books.", "I love to read books."]),
    s("Sardor futbol o'ynashni yoqtiradi.", "Sardor enjoys playing football.", ["play"], [
      "Sardor enjoys playing soccer.",
      "Sardor likes playing football.",
      "Sardor likes to play football.",
    ]),
    s("Uy vazifasini qilib bo'ldingmi?", "Have you finished doing your homework?", ["do"], ["Did you finish doing your homework?", "Have you finished your homework?", "Did you finish your homework?"]),
    s("Otam chekishni tashladi.", "My father stopped smoking.", ["smoke"], ["My dad stopped smoking.", "My father has stopped smoking.", "My dad has stopped smoking."]),
    s("Men erta turishni yomon ko'raman.", "I hate getting up early.", ["got"], ["I hate to get up early.", "I hate waking up early.", "I hate to wake up early."]),
    s("Zarina rasm chizishni yaxshi biladi.", "Zarina is good at drawing.", ["draw"]),
    s("Men ovqat pishirishni yaxshi bilmayman.", "I'm not good at cooking.", ["cook"]),
    s("Sevara qo'shiq aytishni yaxshi ko'radi.", "Sevara loves singing.", ["sings"], ["Sevara loves to sing.", "Sevara likes singing.", "Sevara likes to sing."]),
    s("Biz sayohat qilishni yaxshi ko'ramiz.", "We love travelling.", ["travels"], ["We love traveling.", "We love to travel.", "We like travelling.", "We like traveling.", "We like to travel."]),
    s("Men kutishga qarshi emasman.", "I don't mind waiting.", ["wait"]),
    s("Men bugun chiqishni xohlamayman.", "I don't want to go out today.", ["going"], ["Today I don't want to go out."]),
    s("Sen nima qilmoqchisan?", "What do you want to do?", ["doing"]),
    s("Siz qahva ichishni xohlaysizmi?", "Would you like to drink coffee?", ["drinking"], ["Would you like to drink some coffee?"]),
    s("Ular ishlashni to'xtatishdi va dam olishdi.", "They stopped working and had a rest.", ["work"], ["They stopped working and rested."]),
    s("Men har kuni yugurishni yoqtiraman.", "I like running every day.", ["runs"], ["I like to run every day.", "I enjoy running every day."]),
    s("Jasur haydashni o'rganmoqchi.", "Jasur wants to learn to drive.", ["driving"], ["Jasur wants to learn how to drive."]),
    s("Men ingliz tilida gapirishni yaxshi ko'raman.", "I love speaking English.", ["speaks"], ["I love to speak English.", "I like speaking English.", "I like to speak English."]),
    s("Biz uyni tozalashni tugatdik.", "We finished cleaning the house.", ["clean"]),
    s("U (qiz) shifokor bo'lishga umid qiladi.", "She hopes to become a doctor.", ["becoming"], ["She hopes to be a doctor."]),
    s("Akam musiqa tinglashni yoqtiradi.", "My brother enjoys listening to music.", ["listen"], [
      "My brother likes listening to music.",
      "My brother likes to listen to music.",
      "My brother loves listening to music.",
    ]),
    s("Men yangi telefon sotib olishga qaror qildim.", "I decided to buy a new phone.", ["buying"]),
    s("Uxlashdan oldin men kitob o'qiyman.", "Before going to bed, I read a book.", ["go"], ["I read a book before going to bed."]),
  ],
  test: [
    s("Men Samarqandga borishni xohlayman.", "I want to go to Samarkand.", ["going"], ["I want to visit Samarkand."]),
    s("Madina o'qituvchi bo'lishni xohlaydi.", "Madina wants to be a teacher.", ["being"], ["Madina wants to become a teacher."]),
    s("Men ko'proq uxlashim kerak.", "I need to sleep more.", ["sleeping"]),
    s("Biz uyga qaytishga qaror qildik.", "We decided to go home.", ["going"], ["We decided to return home."]),
    s("Men bir stakan suv ichmoqchi edim.", "I would like to drink a glass of water.", ["drinking"], ["I'd like to drink a glass of water.", "I would like a glass of water.", "I'd like a glass of water."]),
    s("Ali ingliz tilini o'rganishga umid qiladi.", "Ali hopes to learn English.", ["learning"], ["Ali hopes to study English."]),
    s("Men suzishni yoqtiraman.", "I enjoy swimming.", ["to"], ["I like swimming.", "I like to swim.", "I love swimming.", "I love to swim."]),
    s("Kamola ovqat pishirishni yaxshi ko'radi.", "Kamola loves cooking.", ["cooks"], ["Kamola loves to cook.", "Kamola likes cooking.", "Kamola likes to cook."]),
    s("Yomg'ir yog'ishdan to'xtadi.", "It stopped raining.", ["rain"], ["It has stopped raining."]),
    s("Men kitobni o'qib bo'ldim.", "I finished reading the book.", ["read"], ["I have finished reading the book."]),
    s("Timur matematikani yaxshi biladi.", "Timur is good at maths.", ["in"], ["Timur is good at math.", "Timur is good at mathematics."]),
    s("U (yigit) suzishni yaxshi biladi.", "He is good at swimming.", ["swim"]),
    s("Men idish yuvishni yomon ko'raman.", "I hate washing the dishes.", ["wash"], ["I hate to wash the dishes.", "I hate washing dishes.", "I hate to wash dishes."]),
    s("Men yordam berishga qarshi emasman.", "I don't mind helping.", ["help"], ["I don't mind helping you."]),
    s("Biz bugun ishlashni xohlamaymiz.", "We don't want to work today.", ["working"], ["Today we don't want to work."]),
    s("Siz choy ichishni xohlaysizmi?", "Would you like to drink tea?", ["drinking"], ["Would you like to drink some tea?", "Would you like some tea?", "Would you like tea?"]),
    s("Zarina gitara chalishni o'rganyapti.", "Zarina is learning to play the guitar.", ["playing"], ["Zarina is learning to play guitar."]),
    s("Ular futbol o'ynashni tugatishdi.", "They finished playing football.", ["play"], ["They finished playing soccer."]),
    s("Sen ertaga nima qilmoqchisan?", "What do you want to do tomorrow?", ["doing"], ["Tomorrow what do you want to do?"]),
    s("Men har kuni ertalab yugurishni yoqtiraman.", "I enjoy running every morning.", ["run"], ["I like running every morning.", "I like to run every morning."]),
  ],
};

/* ───────────────────────────── 11. Past Simple ───────────────────────────── */

const PAST_SIMPLE: GrammarTopicContent = {
  slug: "a1-past-simple",
  level: "A1",
  position: 11,
  title: { en: "Past Simple", uz: "Past Simple (o'tgan zamon)" },
  explanation: {
    uz: [
      "Past Simple o'tmishda tugagan ish uchun: yesterday, last week, two days ago, in 2020.",
      "To be: I / he / she / it + was; we / you / they + were: I was at home yesterday.",
      "To'g'ri fe'llarga -ed qo'shiladi: work - worked, play - played, study - studied, stop - stopped.",
      "Noto'g'ri fe'llarni yodlash kerak: go - went, see - saw, eat - ate, buy - bought, have - had, come - came.",
      "Inkor: didn't + fe'lning oddiy shakli: I didn't go (didn't went emas!). was / were bilan: wasn't, weren't.",
      "So'roq: Did + ega + oddiy fe'l: Did you see Ali? Where did you go? Was she at home?",
    ].join("\n"),
    pattern: "subject + verb-ed / irregular past · was / were · not: didn't + verb, wasn't / weren't · question: Did + subject + verb …? / Was / Were …?",
    examples: [
      { en: "I watched a film yesterday.", uz: "Kecha men film ko'rdim." },
      { en: "We went to Samarkand last summer.", uz: "O'tgan yozda biz Samarqandga bordik." },
      { en: "She didn't come to school.", uz: "U maktabga kelmadi." },
      { en: "Where were you yesterday?", uz: "Kecha qayerda eding?" },
    ],
  },
  build: [
    s("Kecha men uyda edim.", "I was at home yesterday.", ["were"], ["Yesterday I was at home."]),
    s("Ular o'tgan hafta Buxoroda edi.", "They were in Bukhara last week.", ["was"], ["Last week they were in Bukhara."]),
    s("Film juda qiziq edi.", "The film was very interesting.", ["were"], ["The movie was very interesting."]),
    s("Kecha men film ko'rdim.", "I watched a film yesterday.", ["watch"], ["I watched a movie yesterday.", "Yesterday I watched a film.", "Yesterday I watched a movie."]),
    s("Biz kecha futbol o'ynadik.", "We played football yesterday.", ["play"], ["We played soccer yesterday.", "Yesterday we played football.", "Yesterday we played soccer."]),
    s("Madina ikki yil oldin Londonda yashagan.", "Madina lived in London two years ago.", ["live"]),
    s("O'tgan yozda biz Samarqandga bordik.", "We went to Samarkand last summer.", ["goed"], ["Last summer we went to Samarkand."]),
    s("Men nonushtaga tuxum yedim.", "I ate eggs for breakfast.", ["eated"], ["I had eggs for breakfast."]),
    s("Ali yangi telefon sotib oldi.", "Ali bought a new phone.", ["buyed"]),
    s("Men kecha Sardorni ko'rdim.", "I saw Sardor yesterday.", ["seed"], ["Yesterday I saw Sardor."]),
    s("Ular soat o'nda keldi.", "They came at ten o'clock.", ["comed"], ["They came at ten.", "They arrived at ten o'clock.", "They arrived at ten."]),
    s("Malika menga xat yozdi.", "Malika wrote me a letter.", ["writed"], ["Malika wrote a letter to me."]),
    s("Otam o'tgan hafta Toshkentga ketdi.", "My father went to Tashkent last week.", ["go"], ["My dad went to Tashkent last week.", "Last week my father went to Tashkent."]),
    s("Men kecha maktabga bormadim.", "I didn't go to school yesterday.", ["went"], ["Yesterday I didn't go to school."]),
    s("U (qiz) uy vazifasini qilmadi.", "She didn't do her homework.", ["did"], ["She didn't do the homework."]),
    s("Biz televizor ko'rmadik.", "We didn't watch TV.", ["watched"]),
    s("Jasur kecha uyda emas edi.", "Jasur wasn't at home yesterday.", ["weren't"], ["Yesterday Jasur wasn't at home."]),
    s("Ular darsda emas edi.", "They weren't in class.", ["wasn't"], ["They weren't in the lesson."]),
    s("Men uni tushunmadim.", "I didn't understand him.", ["understood"], ["I didn't understand it.", "I didn't understand her."]),
    s("Kecha Alini ko'rdingmi?", "Did you see Ali yesterday?", ["saw"], ["Yesterday did you see Ali?"]),
    s("Madina dam olishda qayerga bordi?", "Where did Madina go on holiday?", ["went"], ["Where did Madina go on vacation?"]),
    s("Kecha qayerda eding?", "Where were you yesterday?", ["was"]),
    s("Film yaxshi bo'ldimi?", "Was the film good?", ["were"], ["Was the movie good?"]),
    s("Nonushtaga nima yeding?", "What did you eat for breakfast?", ["ate"], ["What did you have for breakfast?"]),
    s("Siz uy vazifasini qildingizmi? Ha, qildim.", "Did you do your homework? Yes, I did.", ["done"], ["Did you do the homework? Yes, I did."]),
    s("Ular kecha keldimi? Yo'q, kelmadi.", "Did they come yesterday? No, they didn't.", ["came"]),
    s("Men kitobni o'qidim va uxladim.", "I read the book and went to sleep.", ["go"], ["I read the book and went to bed."]),
    s("Uch kun oldin men buvimga qo'ng'iroq qildim.", "I called my grandmother three days ago.", ["call"], ["I called my grandma three days ago.", "I phoned my grandmother three days ago."]),
    s("Biz kecha restoranda kechki ovqat yedik.", "We had dinner in a restaurant yesterday.", ["have"], [
      "We had dinner at a restaurant yesterday.",
      "Yesterday we had dinner in a restaurant.",
      "Yesterday we had dinner at a restaurant.",
    ]),
    s("2020-yilda men maktabni tugatdim.", "I finished school in 2020.", ["finish"], ["In 2020 I finished school."]),
  ],
  test: [
    s("Kecha men kasal edim.", "I was ill yesterday.", ["were"], ["I was sick yesterday.", "Yesterday I was ill.", "Yesterday I was sick."]),
    s("Biz o'tgan yili Toshkentda edik.", "We were in Tashkent last year.", ["was"], ["Last year we were in Tashkent."]),
    s("Kecha men ingliz tilini o'rgandim.", "I studied English yesterday.", ["study"], ["I learned English yesterday.", "Yesterday I studied English.", "Yesterday I learned English."]),
    s("Ular parkda yurishdi.", "They walked in the park.", ["walk"]),
    s("Kamola kecha go'zal ko'ylak sotib oldi.", "Kamola bought a beautiful dress yesterday.", ["buyed"], ["Yesterday Kamola bought a beautiful dress."]),
    s("Men o'tgan hafta Zarinani ko'rdim.", "I saw Zarina last week.", ["seed"], ["Last week I saw Zarina."]),
    s("Biz kecha kinoga bordik.", "We went to the cinema yesterday.", ["goed"], ["We went to the movies yesterday.", "Yesterday we went to the cinema.", "Yesterday we went to the movies."]),
    s("Otam kecha kech keldi.", "My father came home late yesterday.", ["comed"], ["My dad came home late yesterday.", "Yesterday my father came home late."]),
    s("Men kecha televizor ko'rmadim.", "I didn't watch TV yesterday.", ["watched"], ["Yesterday I didn't watch TV."]),
    s("Sardor maktabga bormadi.", "Sardor didn't go to school.", ["went"]),
    s("Biz uyda emas edik.", "We weren't at home.", ["wasn't"]),
    s("Choy issiq emas edi.", "The tea wasn't hot.", ["weren't"]),
    s("Kecha Madinaga qo'ng'iroq qildingmi?", "Did you call Madina yesterday?", ["called"], ["Did you phone Madina yesterday?", "Yesterday did you call Madina?"]),
    s("O'tgan yozda qayerga bording?", "Where did you go last summer?", ["went"]),
    s("Kecha soat sakkizda qayerda eding?", "Where were you at eight o'clock yesterday?", ["was"], ["Where were you at eight yesterday?", "Yesterday where were you at eight o'clock?"]),
    s("Kechki ovqatga nima yedingiz?", "What did you eat for dinner?", ["ate"], ["What did you have for dinner?"]),
    s("Ali kecha keldimi? Ha, keldi.", "Did Ali come yesterday? Yes, he did.", ["came"]),
    s("Dars qiyin bo'ldimi? Yo'q.", "Was the lesson difficult? No, it wasn't.", ["were"], ["Was the lesson hard? No, it wasn't."]),
    s("Men nonushta qildim va ishga ketdim.", "I had breakfast and went to work.", ["go"], ["I ate breakfast and went to work."]),
    s("Ikki kun oldin biz yangi kompyuter sotib oldik.", "We bought a new computer two days ago.", ["buy"]),
  ],
};

/* ───────────────────────────── 12. Prepositions ───────────────────────────── */

const PREPOSITIONS: GrammarTopicContent = {
  slug: "a1-prepositions",
  level: "A1",
  position: 12,
  title: { en: "Prepositions (in, on, at, under …)", uz: "Predloglar (in, on, at, under …)" },
  explanation: {
    uz: [
      "Joy: in - ichida (in the box, in Tashkent), on - ustida (on the table, on the wall), at - nuqtada (at home, at school, at the bus stop).",
      "under - tagida, next to - yonida, between - orasida, behind - orqasida, in front of - oldida, near - yaqinida.",
      "Vaqt: at + soat (at 7 o'clock, at night), on + kun / sana (on Monday, on 5 May), in + oy / yil / fasl (in June, in 2024, in summer).",
      "Kunning qismlari: in the morning, in the afternoon, in the evening, lekin at night.",
      "Dam olish kunlari: at the weekend (Britaniya) yoki on the weekend (Amerika) - ikkalasi ham to'g'ri.",
    ].join("\n"),
    pattern: "place: in / on / at / under / next to / between / behind / in front of · time: at + clock time, on + day / date, in + month / year / season",
    examples: [
      { en: "The keys are on the table.", uz: "Kalitlar stol ustida." },
      { en: "The cat is under the bed.", uz: "Mushuk karavot tagida." },
      { en: "The lesson starts at nine o'clock.", uz: "Dars soat to'qqizda boshlanadi." },
      { en: "My birthday is in May.", uz: "Mening tug'ilgan kunim mayda." },
    ],
  },
  build: [
    s("Kalitlar stol ustida.", "The keys are on the table.", ["in"]),
    s("Mushuk karavot tagida.", "The cat is under the bed.", ["on"]),
    s("Kitob sumkamda.", "The book is in my bag.", ["on"]),
    s("Devorda rasm bor.", "There is a picture on the wall.", ["in"]),
    s("Men uydaman.", "I am at home.", ["in"]),
    s("Bolalar maktabda.", "The children are at school.", ["on"], ["The kids are at school."]),
    s("Biz Toshkentda yashaymiz.", "We live in Tashkent.", ["at"]),
    s("Bank pochta yonida.", "The bank is next to the post office.", ["between"], ["The bank is near the post office."]),
    s("Do'kon bank va kafe orasida.", "The shop is between the bank and the cafe.", ["next"], ["The shop is between the cafe and the bank."]),
    s("Bog' uyning orqasida.", "The garden is behind the house.", ["front"]),
    s("Mashina uyning oldida.", "The car is in front of the house.", ["behind"]),
    s("Avtobus bekatida kutaman.", "I'll wait at the bus stop.", ["on"], ["I will wait at the bus stop."]),
    s("Dars soat to'qqizda boshlanadi.", "The lesson starts at nine o'clock.", ["in"], ["The lesson starts at nine.", "The lesson begins at nine o'clock.", "The lesson begins at nine."]),
    s("Men dushanba kuni ishlayman.", "I work on Monday.", ["in"], ["I work on Mondays."]),
    s("Mening tug'ilgan kunim mayda.", "My birthday is in May.", ["on"]),
    s("Biz yozda dengizga boramiz.", "We go to the sea in summer.", ["on"], ["We go to the sea in the summer."]),
    s("Men ertalab yuguraman.", "I run in the morning.", ["on"], ["I go running in the morning."]),
    s("Kechasi men uxlayman.", "I sleep at night.", ["in"]),
    s("Ali 2010-yilda tug'ilgan.", "Ali was born in 2010.", ["on"]),
    s("Malika 5-martda tug'ilgan.", "Malika was born on 5 March.", ["in"], ["Malika was born on the fifth of March.", "Malika was born on March 5."]),
    s("Biz kechqurun televizor ko'ramiz.", "We watch TV in the evening.", ["at"]),
    s("Yangi yil kechasi biz uyda bo'lamiz.", "We are at home on New Year's Eve.", ["in"]),
    s("Telefoning qayerda? Divan ustida.", "Where is your phone? It's on the sofa.", ["in"], ["Where is your phone? It is on the sofa."]),
    s("Uyim park yaqinida.", "My house is near the park.", ["at"], ["My house is next to the park."]),
    s("Mening ismim ro'yxatda.", "My name is on the list.", ["in"]),
    s("Otam mashinada.", "My father is in the car.", ["on"], ["My dad is in the car."]),
    s("Biz avtobusdamiz.", "We are on the bus.", ["at"]),
    s("Ular hozir ishda.", "They are at work now.", ["on"], ["They are at work right now."]),
    s("Men shanba kuni ertalab futbol o'ynayman.", "I play football on Saturday morning.", ["in"], ["I play soccer on Saturday morning.", "I play football on Saturday mornings."]),
    s("Sumka stul tagida, kitob esa stol ustida.", "The bag is under the chair and the book is on the table.", ["in"], [
      "The bag is under the chair, and the book is on the table.",
    ]),
  ],
  test: [
    s("Telefon stol ustida.", "The phone is on the table.", ["in"], ["The phone is on the desk."]),
    s("It stol tagida.", "The dog is under the table.", ["on"]),
    s("Pul hamyonimda.", "The money is in my wallet.", ["on"]),
    s("Otam ishda.", "My father is at work.", ["in"], ["My dad is at work."]),
    s("Ular Samarqandda yashaydi.", "They live in Samarkand.", ["at"]),
    s("Dorixona bank yonida.", "The pharmacy is next to the bank.", ["between"], ["The pharmacy is near the bank."]),
    s("Maktab park va kasalxona orasida.", "The school is between the park and the hospital.", ["next"], ["The school is between the hospital and the park."]),
    s("Mushuk eshik orqasida.", "The cat is behind the door.", ["front"]),
    s("Biz kinoteatr oldida kutamiz.", "We will wait in front of the cinema.", ["behind"], ["We'll wait in front of the cinema."]),
    s("Film soat yettida boshlanadi.", "The film starts at seven o'clock.", ["in"], [
      "The film starts at seven.",
      "The movie starts at seven o'clock.",
      "The movie starts at seven.",
      "The film begins at seven o'clock.",
      "The movie begins at seven o'clock.",
    ]),
    s("Biz juma kuni uchrashamiz.", "We meet on Friday.", ["in"], ["We meet on Fridays.", "We will meet on Friday.", "We'll meet on Friday."]),
    s("Mening tug'ilgan kunim iyulda.", "My birthday is in July.", ["on"]),
    s("Qishda havo sovuq.", "It is cold in winter.", ["on"], ["It is cold in the winter.", "In winter it is cold.", "In winter the weather is cold."]),
    s("Men tushdan keyin uxlayman.", "I sleep in the afternoon.", ["on"]),
    s("Sardor 2008-yilda tug'ilgan.", "Sardor was born in 2008.", ["on"]),
    s("Biz kechasi ishlamaymiz.", "We don't work at night.", ["in"]),
    s("Kitoblaring qayerda? Javonda.", "Where are your books? They are on the shelf.", ["in"]),
    s("Onam oshxonada.", "My mother is in the kitchen.", ["on"], ["My mom is in the kitchen.", "My mum is in the kitchen."]),
    s("Biz poyezddamiz.", "We are on the train.", ["at"]),
    s("Men har kuni ertalab soat yettida turaman.", "I get up at seven o'clock every morning.", ["in"], [
      "I get up at seven every morning.",
      "Every morning I get up at seven o'clock.",
      "Every morning I get up at seven.",
    ]),
  ],
};

/* ───────────────────────────── 13. Future Simple ───────────────────────────── */

const FUTURE_SIMPLE: GrammarTopicContent = {
  slug: "a1-future-simple",
  level: "A1",
  position: 13,
  title: { en: "Future Simple (will)", uz: "Future Simple (will - kelasi zamon)" },
  explanation: {
    uz: [
      "Will kelajak haqida: bashorat, va'da, hozir qabul qilingan qaror: I will help you = Men senga yordam beraman.",
      "Will hamma shaxs bilan bir xil: I will, she will, they will. Qisqasi: I'll, she'll, they'll.",
      "Will dan keyin fe'l oddiy shaklda, to qo'shilmaydi: She will come (will comes emas, will to come emas).",
      "Inkor: won't (will not): I won't be late.",
      "So'roq: Will + ega + fe'l: Will you come tomorrow? Qisqa javob: Yes, I will. / No, I won't.",
      "Ko'p ishlatiladigan so'zlar: tomorrow, next week, next year, soon, in 2030, I think …, maybe.",
    ].join("\n"),
    pattern: "subject + will ('ll) + verb · not: won't + verb · question: Will + subject + verb …?",
    examples: [
      { en: "I will call you tomorrow.", uz: "Ertaga senga qo'ng'iroq qilaman." },
      { en: "It will rain tonight.", uz: "Bugun kechasi yomg'ir yog'adi." },
      { en: "I won't be late.", uz: "Men kech qolmayman." },
      { en: "Will you help me?", uz: "Menga yordam berasanmi?" },
    ],
  },
  build: [
    s("Ertaga senga qo'ng'iroq qilaman.", "I will call you tomorrow.", ["to"], ["I'll call you tomorrow.", "Tomorrow I will call you."]),
    s("Bugun kechasi yomg'ir yog'adi.", "It will rain tonight.", ["rains"], ["It will rain this evening."]),
    s("Madina keyingi yili universitetga kiradi.", "Madina will go to university next year.", ["goes"], ["Next year Madina will go to university."]),
    s("Men senga yordam beraman.", "I will help you.", ["helps"], ["I'll help you."]),
    s("Ular ertaga keladi.", "They will come tomorrow.", ["comes"], ["They'll come tomorrow.", "Tomorrow they will come."]),
    s("Menimcha, u (qiz) imtihondan o'tadi.", "I think she will pass the exam.", ["passes"], ["I think she'll pass the exam."]),
    s("Biz tez orada uchrashamiz.", "We will meet soon.", ["to"], ["We'll meet soon."]),
    s("Ali o'n sakkiz yoshda bo'ladi.", "Ali will be eighteen.", ["is"], ["Ali will be eighteen years old."]),
    s("Men eshikni ochaman.", "I'll open the door.", ["opening"], ["I will open the door."]),
    s("Kelajakda odamlar Marsda yashaydi.", "People will live on Mars in the future.", ["lives"], ["In the future people will live on Mars."]),
    s("Men kech qolmayman.", "I won't be late.", ["am"]),
    s("Ular bizga yordam bermaydi.", "They won't help us.", ["don't"]),
    s("Ertaga qor yog'maydi.", "It won't snow tomorrow.", ["doesn't"], ["Tomorrow it won't snow."]),
    s("Sardor bu yil ishlamaydi.", "Sardor won't work this year.", ["works"]),
    s("Men buni hech kimga aytmayman.", "I won't tell anybody.", ["don't"], ["I won't tell anyone.", "I won't tell anybody about it.", "I won't tell anyone about it."]),
    s("Xavotir olma, bu qiyin bo'lmaydi.", "Don't worry, it won't be difficult.", ["isn't"], ["Don't worry, it won't be hard."]),
    s("Ertaga kelasanmi?", "Will you come tomorrow?", ["do"], ["Tomorrow will you come?"]),
    s("Menga yordam berasanmi?", "Will you help me?", ["are"]),
    s("U (yigit) bizga qo'ng'iroq qiladimi?", "Will he call us?", ["calls"], ["Will he phone us?"]),
    s("Ertaga havo issiq bo'ladimi?", "Will it be hot tomorrow?", ["is"], ["Will it be warm tomorrow?"]),
    s("Qachon qaytasiz?", "When will you come back?", ["do"], ["When will you return?", "When will you be back?"]),
    s("Ziyofatga kim keladi?", "Who will come to the party?", ["comes"]),
    s("Sen keyingi hafta qayerda bo'lasan?", "Where will you be next week?", ["are"]),
    s("Ular kelishadimi? Ha, kelishadi.", "Will they come? Yes, they will.", ["do"]),
    s("Malika bizni kutadimi? Yo'q.", "Will Malika wait for us? No, she won't.", ["does"]),
    s("Choy ichasanmi? Ha, rahmat, ichaman.", "Will you have some tea? Yes, I will.", ["do"], ["Will you have tea? Yes, I will."]),
    s("Sumka og'ir. Men senga yordam beraman.", "The bag is heavy. I'll help you.", ["helping"], ["The bag is heavy. I will help you."]),
    s("2030-yilda men o'ttiz yoshda bo'laman.", "I will be thirty in 2030.", ["am"], ["In 2030 I will be thirty.", "I'll be thirty in 2030."]),
    s("Balki ertaga biz parkka boramiz.", "Maybe we will go to the park tomorrow.", ["going"], ["Maybe we'll go to the park tomorrow.", "Maybe tomorrow we will go to the park."]),
    s("Men ingliz tilini o'rganaman va Londonga boraman.", "I will learn English and go to London.", ["goes"], ["I'll learn English and go to London."]),
  ],
  test: [
    s("Ertaga men senga xat yozaman.", "I will write to you tomorrow.", ["writes"], ["I'll write to you tomorrow.", "Tomorrow I will write to you."]),
    s("Ertaga havo issiq bo'ladi.", "It will be hot tomorrow.", ["is"], ["It will be warm tomorrow.", "Tomorrow it will be hot.", "Tomorrow it will be warm."]),
    s("Zarina keyingi oy Toshkentga boradi.", "Zarina will go to Tashkent next month.", ["goes"], ["Next month Zarina will go to Tashkent."]),
    s("Biz senga yordam beramiz.", "We will help you.", ["helps"], ["We'll help you."]),
    s("Menimcha, ular g'alaba qozonadi.", "I think they will win.", ["wins"], ["I think they'll win."]),
    s("Men derazani yopaman.", "I'll close the window.", ["closing"], ["I will close the window."]),
    s("Men ertaga ishlamayman.", "I won't work tomorrow.", ["don't"], ["Tomorrow I won't work."]),
    s("Ali kech qolmaydi.", "Ali won't be late.", ["isn't"]),
    s("Bugun yomg'ir yog'maydi.", "It won't rain today.", ["doesn't"], ["Today it won't rain."]),
    s("Xavotir olma, men unutmayman.", "Don't worry, I won't forget.", ["forgets"]),
    s("Ertaga maktabga borasanmi?", "Will you go to school tomorrow?", ["do"], ["Tomorrow will you go to school?"]),
    s("Madina bizga yordam beradimi?", "Will Madina help us?", ["does"]),
    s("Film qachon tugaydi?", "When will the film finish?", ["does"], ["When will the movie finish?", "When will the film end?", "When will the movie end?"]),
    s("Keyingi yili qayerda yashaysan?", "Where will you live next year?", ["do"]),
    s("Ertaga qor yog'adimi?", "Will it snow tomorrow?", ["does"], ["Tomorrow will it snow?"]),
    s("Sen kelasanmi? Ha, kelaman.", "Will you come? Yes, I will.", ["do"]),
    s("Ular bizni kutishadimi? Yo'q.", "Will they wait for us? No, they won't.", ["do"]),
    s("Telefon jiringlayapti. Men javob beraman.", "The phone is ringing. I'll answer it.", ["answering"], ["The phone is ringing. I will answer it."]),
    s("Balki keyingi hafta biz uchrashamiz.", "Maybe we will meet next week.", ["meeting"], ["Maybe we'll meet next week.", "Maybe next week we will meet."]),
    s("Kelajakda men shifokor bo'laman.", "I will be a doctor in the future.", ["am"], ["In the future I will be a doctor.", "I'll be a doctor in the future."]),
  ],
};

/* ───────────────────────────── 14. Question words ───────────────────────────── */

const QUESTION_WORDS: GrammarTopicContent = {
  slug: "a1-question-words",
  level: "A1",
  position: 14,
  title: { en: "Question words (what, where, when …)", uz: "So'roq so'zlari (what, where, when …)" },
  explanation: {
    uz: [
      "What - nima, Where - qayerda / qayerga, When - qachon, Who - kim, Why - nega, How - qanday.",
      "Which - qaysi (tanlov bor), Whose - kimning, What time - soat nechada.",
      "How old - necha yosh, How many - nechta (sanaladigan), How much - qancha (sanalmaydigan, narx).",
      "So'roq so'zi gapning boshida, keyin to be yoki do / does / did: Where are you? Where do you live?",
      "Who ega bo'lsa do / does kerak emas: Who lives here? (Who does live emas).",
    ].join("\n"),
    pattern: "Question word + am / is / are + subject …? · Question word + do / does / did + subject + verb …? · Who + verb-s …?",
    examples: [
      { en: "Where do you live?", uz: "Qayerda yashaysan?" },
      { en: "What time is it?", uz: "Soat necha?" },
      { en: "How many brothers have you got?", uz: "Nechta akang bor?" },
      { en: "Why are you sad?", uz: "Nega xafasan?" },
    ],
  },
  build: [
    s("Ismingiz nima?", "What is your name?", ["where"]),
    s("Qayerda yashaysan?", "Where do you live?", ["what"]),
    s("Tug'ilgan kuning qachon?", "When is your birthday?", ["where"]),
    s("U (qiz) kim?", "Who is she?", ["whose"]),
    s("Nega xafasan?", "Why are you sad?", ["how"]),
    s("Qalaysan?", "How are you?", ["who"]),
    s("Soat necha?", "What time is it?", ["when"], ["What is the time?"]),
    s("Necha yoshdasan?", "How old are you?", ["much"]),
    s("Nechta akang bor?", "How many brothers have you got?", ["much"], ["How many brothers do you have?"]),
    s("Bu ko'ylak qancha turadi?", "How much is this shirt?", ["many"], ["How much does this shirt cost?"]),
    s("Bu kimning telefoni?", "Whose phone is this?", ["who"]),
    s("Qaysi rangni yoqtirasan, qizilmi yoki ko'kmi?", "Which colour do you like, red or blue?", ["who"], [
      "Which color do you like, red or blue?",
      "Which colour do you prefer, red or blue?",
      "Which color do you prefer, red or blue?",
    ]),
    s("Nima qilyapsan?", "What are you doing?", ["where"]),
    s("Qayerga ketyapsan?", "Where are you going?", ["who"]),
    s("Dars soat nechada boshlanadi?", "What time does the lesson start?", ["when"], ["When does the lesson start?", "What time does the lesson begin?", "When does the lesson begin?"]),
    s("Bu yerda kim yashaydi?", "Who lives here?", ["does"]),
    s("Sevimli taomingiz nima?", "What is your favourite food?", ["which"], ["What is your favorite food?", "What's your favourite food?", "What's your favorite food?"]),
    s("Maktabga qanday borasan?", "How do you go to school?", ["what"], ["How do you get to school?"]),
    s("Nega u (yigit) kech qoldi?", "Why was he late?", ["how"]),
    s("Kecha qayerda eding?", "Where were you yesterday?", ["when"]),
    s("Sinfingizda nechta o'quvchi bor?", "How many students are in your class?", ["much"], [
      "How many students are there in your class?",
      "How many pupils are in your class?",
      "How many pupils are there in your class?",
    ]),
    s("Sizga qancha suv kerak?", "How much water do you need?", ["many"]),
    s("Qachon uyga kelasan?", "When will you come home?", ["where"], ["When are you coming home?"]),
    s("Bu xatni kim yozdi?", "Who wrote this letter?", ["did"]),
    s("Qaysi avtobus markazga boradi?", "Which bus goes to the centre?", ["who"], ["Which bus goes to the center?", "Which bus goes to the city centre?", "Which bus goes to the city center?"]),
    s("Akangning ismi nima?", "What is your brother's name?", ["who"], ["What's your brother's name?"]),
    s("Nega ingliz tilini o'rganyapsan?", "Why are you learning English?", ["what"], ["Why are you studying English?"]),
    s("Ota-onang qayerda ishlaydi?", "Where do your parents work?", ["does"]),
    s("Kitobni qayerdan sotib olding?", "Where did you buy the book?", ["when"], ["Where did you buy this book?"]),
    s("Dam olish kunlari nima qilasan?", "What do you do at the weekend?", ["where"], ["What do you do on the weekend?", "What do you do at weekends?", "What do you do on weekends?"]),
  ],
  test: [
    s("Familiyangiz nima?", "What is your surname?", ["where"], ["What's your surname?", "What is your last name?", "What's your last name?", "What is your family name?"]),
    s("Qayerda ishlaysiz?", "Where do you work?", ["what"]),
    s("Imtihon qachon?", "When is the exam?", ["where"]),
    s("Bu odam kim?", "Who is this man?", ["whose"], ["Who is this person?", "Who is that man?"]),
    s("Nega charchading?", "Why are you tired?", ["how"]),
    s("Ota-onang qalay?", "How are your parents?", ["who"]),
    s("Film soat nechada boshlanadi?", "What time does the film start?", ["when"], [
      "When does the film start?",
      "What time does the movie start?",
      "When does the movie start?",
    ]),
    s("Akang necha yoshda?", "How old is your brother?", ["much"]),
    s("Nechta kitobing bor?", "How many books have you got?", ["much"], ["How many books do you have?"]),
    s("Bu sumka qancha turadi?", "How much is this bag?", ["many"], ["How much does this bag cost?"]),
    s("Bu kimning kitobi?", "Whose book is this?", ["who"]),
    s("Qaysi biri seniki?", "Which one is yours?", ["who"]),
    s("Ular nima qilyapti?", "What are they doing?", ["where"]),
    s("Bu mashinani kim haydaydi?", "Who drives this car?", ["does"]),
    s("Ishga qanday borasiz?", "How do you go to work?", ["what"], ["How do you get to work?"]),
    s("Kecha nega kelmading?", "Why didn't you come yesterday?", ["how"]),
    s("Kunda qancha choy ichasan?", "How much tea do you drink a day?", ["many"], ["How much tea do you drink every day?", "How much tea do you drink each day?"]),
    s("O'tgan yozda qayerga bording?", "Where did you go last summer?", ["when"]),
    s("Sevimli fasling qaysi?", "What is your favourite season?", ["who"], ["What is your favorite season?", "Which is your favourite season?", "Which is your favorite season?"]),
    s("Uyga qachon qaytasan?", "When will you come back home?", ["where"], ["When are you coming back home?", "When will you be back home?"]),
  ],
};

/* ───────────────────────────── 15. Linkers ───────────────────────────── */

const LINKERS: GrammarTopicContent = {
  slug: "a1-linkers",
  level: "A1",
  position: 15,
  title: { en: "Linkers: and, but, or, because, so", uz: "Bog'lovchilar: and, but, or, because, so" },
  explanation: {
    uz: [
      "and - va: I like tea and coffee.",
      "but - lekin, ammo (qarama-qarshi fikr): The flat is small but nice.",
      "or - yoki (tanlov): Do you want tea or coffee? Inkorda ham: I don't eat meat or fish.",
      "because - chunki (sabab): I'm tired because I worked a lot.",
      "so - shuning uchun (natija): I was tired, so I went to bed.",
      "then - keyin (ketma-ketlik): I had breakfast, then I went to school.",
      "Diqqat: because = sabab, so = natija. It was cold, so I stayed home = I stayed home because it was cold.",
    ].join("\n"),
    pattern: "A and B · A but B · A or B · result because reason · reason, so result · first A, then B",
    examples: [
      { en: "I like tea and coffee.", uz: "Men choy va qahvani yaxshi ko'raman." },
      { en: "The flat is small but nice.", uz: "Kvartira kichik, lekin yaxshi." },
      { en: "I'm hungry because I didn't have breakfast.", uz: "Men ochman, chunki nonushta qilmadim." },
      { en: "It was cold, so we stayed at home.", uz: "Havo sovuq edi, shuning uchun uyda qoldik." },
    ],
  },
  build: [
    s("Men choy va qahvani yaxshi ko'raman.", "I like tea and coffee.", ["but"], ["I like coffee and tea.", "I love tea and coffee."]),
    s("Ali va Sardor do'st.", "Ali and Sardor are friends.", ["or"], ["Sardor and Ali are friends."]),
    s("Kvartira kichik, lekin yaxshi.", "The flat is small but nice.", ["and"], ["The flat is small, but nice.", "The apartment is small but nice.", "The apartment is small, but nice."]),
    s("Men suza olaman, lekin yaxshi emas.", "I can swim, but not very well.", ["so"], ["I can swim but not very well."]),
    s("Choy yoki qahva xohlaysizmi?", "Do you want tea or coffee?", ["and"], ["Would you like tea or coffee?", "Do you want coffee or tea?"]),
    s("Avtobusda yoki taksida boramizmi?", "Shall we go by bus or by taxi?", ["but"], ["Do we go by bus or by taxi?", "Shall we go by bus or taxi?"]),
    s("Men ochman, chunki nonushta qilmadim.", "I'm hungry because I didn't have breakfast.", ["so"], ["I am hungry because I didn't eat breakfast."]),
    s("U (qiz) uyda, chunki u kasal.", "She is at home because she is ill.", ["so"], ["She is at home because she is sick."]),
    s("Havo sovuq edi, shuning uchun biz uyda qoldik.", "It was cold, so we stayed at home.", ["because"], ["It was cold, so we stayed home."]),
    s("Men charchadim, shuning uchun uxlagani yotdim.", "I was tired, so I went to bed.", ["because"], ["I was tired so I went to bed."]),
    s("Men nonushta qildim, keyin maktabga bordim.", "I had breakfast, then I went to school.", ["because"], ["I had breakfast and then I went to school.", "I had breakfast, and then I went to school."]),
    s("Men go'sht ham, baliq ham yemayman.", "I don't eat meat or fish.", ["and"]),
    s("Malika aqlli va chiroyli.", "Malika is clever and beautiful.", ["but"], ["Malika is smart and beautiful.", "Malika is beautiful and clever."]),
    s("Akam bor, lekin opam yo'q.", "I have got a brother, but I haven't got a sister.", ["because"], ["I have a brother, but I don't have a sister."]),
    s("Biz parkka bordik va futbol o'ynadik.", "We went to the park and played football.", ["but"], ["We went to the park and played soccer."]),
    s("Men ingliz tilini o'rganyapman, chunki Londonga bormoqchiman.", "I'm learning English because I want to go to London.", ["so"], [
      "I'm studying English because I want to go to London.",
    ]),
    s("Yomg'ir yog'yapti, shuning uchun soyabon ol.", "It's raining, so take an umbrella.", ["because"]),
    s("Telefonim eski, lekin yaxshi ishlaydi.", "My phone is old, but it works well.", ["so"], ["My phone is old but it works well."]),
    s("Uyga kelasanmi yoki maktabda qolasanmi?", "Are you coming home or staying at school?", ["and"]),
    s("Men kech qoldim, chunki avtobus kelmadi.", "I was late because the bus didn't come.", ["so"]),
    s("Ali kasal edi, shuning uchun maktabga bormadi.", "Ali was ill, so he didn't go to school.", ["because"], ["Ali was sick, so he didn't go to school."]),
    s("Zarina gitara chaladi va qo'shiq aytadi.", "Zarina plays the guitar and sings.", ["or"], ["Zarina plays guitar and sings."]),
    s("Film uzun edi, lekin qiziq edi.", "The film was long, but it was interesting.", ["so"], [
      "The movie was long, but it was interesting.",
      "The film was long but interesting.",
      "The movie was long but interesting.",
    ]),
    s("Men uy vazifasini qildim, keyin televizor ko'rdim.", "I did my homework, then I watched TV.", ["because"], ["I did my homework and then I watched TV."]),
    s("Sen ham, akang ham ziyofatga kelasizlarmi?", "Are you and your brother coming to the party?", ["or"]),
    s("Biz pul tejayapmiz, chunki mashina sotib olmoqchimiz.", "We are saving money because we want to buy a car.", ["so"]),
    s("Do'kon yopiq edi, shuning uchun hech narsa sotib olmadim.", "The shop was closed, so I didn't buy anything.", ["because"], ["The store was closed, so I didn't buy anything."]),
    s("Choy issiq, lekin juda shirin emas.", "The tea is hot but not very sweet.", ["so"], ["The tea is hot, but not very sweet."]),
    s("Dushanba yoki seshanba kuni kelaman.", "I'll come on Monday or Tuesday.", ["and"], ["I will come on Monday or Tuesday.", "I'll come on Monday or on Tuesday."]),
    s("U (yigit) ingliz tilida gapiradi, chunki u Londonda yashagan.", "He speaks English because he lived in London.", ["so"]),
  ],
  test: [
    s("Men olma va banan sotib oldim.", "I bought apples and bananas.", ["but"], ["I bought bananas and apples.", "I bought an apple and a banana."]),
    s("Kamola va Sevara opa-singil.", "Kamola and Sevara are sisters.", ["or"], ["Sevara and Kamola are sisters."]),
    s("Uy eski, lekin chiroyli.", "The house is old but beautiful.", ["and"], ["The house is old, but beautiful.", "The house is old but nice.", "The house is old, but nice."]),
    s("Sharbat yoki suv xohlaysanmi?", "Do you want juice or water?", ["and"], ["Would you like juice or water?", "Do you want water or juice?"]),
    s("Men charchadim, chunki ko'p ishladim.", "I'm tired because I worked a lot.", ["so"], ["I am tired because I worked hard."]),
    s("Ali uyda qoldi, chunki yomg'ir yog'ayotgan edi.", "Ali stayed at home because it was raining.", ["so"], ["Ali stayed home because it was raining."]),
    s("Men kasal edim, shuning uchun shifokorga bordim.", "I was ill, so I went to the doctor.", ["because"], ["I was sick, so I went to the doctor."]),
    s("Havo issiq edi, shuning uchun biz suzdik.", "It was hot, so we went swimming.", ["because"], ["It was hot, so we swam."]),
    s("Men dush qabul qildim, keyin nonushta qildim.", "I had a shower, then I had breakfast.", ["because"], [
      "I took a shower, then I had breakfast.",
      "I had a shower and then I had breakfast.",
      "I took a shower and then I had breakfast.",
    ]),
    s("U (qiz) choy ham, qahva ham ichmaydi.", "She doesn't drink tea or coffee.", ["and"]),
    s("Sardor baland va kuchli.", "Sardor is tall and strong.", ["but"], ["Sardor is strong and tall."]),
    s("Men gitara chala olaman, lekin pianino chala olmayman.", "I can play the guitar, but I can't play the piano.", ["so"], [
      "I can play guitar, but I can't play piano.",
    ]),
    s("Biz do'konga bordik va non sotib oldik.", "We went to the shop and bought bread.", ["but"], ["We went to the store and bought bread.", "We went to the shop and bought some bread."]),
    s("Men erta turdim, chunki imtihonim bor edi.", "I got up early because I had an exam.", ["so"], ["I woke up early because I had an exam."]),
    s("Avtobus kelmadi, shuning uchun men taksida bordim.", "The bus didn't come, so I took a taxi.", ["because"], ["The bus didn't come, so I went by taxi."]),
    s("Kitob qiziq, lekin juda uzun.", "The book is interesting but very long.", ["so"], ["The book is interesting, but very long.", "The book is interesting, but it is very long."]),
    s("Ertaga yoki indinga qo'ng'iroq qilaman.", "I'll call you tomorrow or the day after tomorrow.", ["and"], ["I will call you tomorrow or the day after tomorrow."]),
    s("Men ingliz tilini yaxshi ko'raman, chunki u qiziq.", "I like English because it is interesting.", ["so"], ["I love English because it is interesting."]),
    s("Men ishimni tugatdim, keyin uyga ketdim.", "I finished my work, then I went home.", ["because"], ["I finished my work and then I went home."]),
    s("Muzlatgich bo'sh, shuning uchun do'konga borishimiz kerak.", "The fridge is empty, so we have to go to the shop.", ["because"], [
      "The fridge is empty, so we need to go to the shop.",
      "The fridge is empty, so we have to go to the store.",
      "The fridge is empty, so we need to go to the store.",
    ]),
  ],
};

export const A1_PART3_TOPICS: GrammarTopicContent[] = [
  INFINITIVE_GERUND,
  PAST_SIMPLE,
  PREPOSITIONS,
  FUTURE_SIMPLE,
  QUESTION_WORDS,
  LINKERS,
];
