/**
 * A1 (Beginner) grammar — topics 4-9: Possessives, Pronouns, There is / are,
 * Present Simple, Present Continuous, Basic modals.
 * Written by Claude as a DRAFT for teacher review (imported unpublished).
 * APPEND-ONLY: never reorder or delete items once shipped — progress keys on
 * (topic slug, kind, position). Validated by tests/grammar-content.test.ts.
 */
import type { GrammarItemContent, GrammarTopicContent } from "@shared/grammar/types";

/** One sentence: Uzbek prompt, model English, traps, and other correct answers. */
const s = (uz: string, en: string, traps: string[], alt?: string[]): GrammarItemContent =>
  alt ? { uz, en, traps, alt } : { uz, en, traps };

/* ───────────────────────────── 4. Possessives ───────────────────────────── */

const POSSESSIVES: GrammarTopicContent = {
  slug: "a1-possessives",
  level: "A1",
  position: 4,
  title: { en: "Possessives (my, your, Ali's)", uz: "Egalik (my, your, Alining)" },
  explanation: {
    uz: [
      "Egalik so'zlari otdan oldin keladi: my book (mening kitobim), your bag (sening sumkang).",
      "I - my, you - your, he - his, she - her, it - its, we - our, they - their.",
      "Kishining ismiga 's qo'shiladi: Ali's car = Alining mashinasi. My brother's room = akamning xonasi.",
      "Ko'plikdagi -s bilan tugaydigan otga faqat ' qo'shiladi: my parents' house = ota-onamning uyi.",
      "Diqqat: its (uning - narsa/hayvon) va it's (it is) har xil! Whose? = Kimning?",
      "Otsiz ishlatilganda: mine, yours, his, hers, ours, theirs: This book is mine.",
    ].join("\n"),
    pattern: "my / your / his / her / its / our / their + noun · name + 's + noun · Whose + noun …? · mine / yours / his / hers / ours / theirs",
    examples: [
      { en: "This is my book.", uz: "Bu mening kitobim." },
      { en: "Ali's car is red.", uz: "Alining mashinasi qizil." },
      { en: "Her name is Madina.", uz: "Uning ismi Madina." },
      { en: "Whose bag is this? It's mine.", uz: "Bu kimning sumkasi? Meniki." },
    ],
  },
  build: [
    s("Bu mening kitobim.", "This is my book.", ["me"]),
    s("Sening sumkang stol ustida.", "Your bag is on the table.", ["you"]),
    s("Uning ismi Ali.", "His name is Ali.", ["he"]),
    s("Uning ismi Madina.", "Her name is Madina.", ["she"]),
    s("Bizning uyimiz katta.", "Our house is big.", ["we"]),
    s("Ularning o'qituvchisi juda yaxshi.", "Their teacher is very good.", ["they"]),
    s("Mushuk qora. Uning ko'zlari yashil.", "The cat is black. Its eyes are green.", ["it's"]),
    s("Alining mashinasi qizil.", "Ali's car is red.", ["Ali"]),
    s("Madinaning onasi shifokor.", "Madina's mother is a doctor.", ["Madina"], ["Madina's mom is a doctor.", "Madina's mum is a doctor."]),
    s("Akamning xonasi kichik.", "My brother's room is small.", ["brother"], ["My older brother's room is small."]),
    s("Otamning ismi Timur.", "My father's name is Timur.", ["father"], ["My dad's name is Timur."]),
    s("Ota-onamning uyi Samarqandda.", "My parents' house is in Samarkand.", ["parent"]),
    s("Bu o'qituvchining stoli.", "This is the teacher's desk.", ["teacher"], ["This is the teacher's table."]),
    s("Bolalarning o'yinchoqlari polda.", "The children's toys are on the floor.", ["children"], ["The kids' toys are on the floor."]),
    s("Bu kitob meniki.", "This book is mine.", ["my"]),
    s("Bu ruchka seniki emas.", "This pen isn't yours.", ["your"]),
    s("Qizil sumka uniki (qizning).", "The red bag is hers.", ["her"]),
    s("Bu mashina bizniki.", "This car is ours.", ["our"]),
    s("O'sha uy ularniki.", "That house is theirs.", ["their"]),
    s("Bu telefon Jasurniki.", "This phone is Jasur's.", ["Jasur"]),
    s("Bu kimning sumkasi?", "Whose bag is this?", ["who's"]),
    s("Bu kimning kitoblari?", "Whose books are these?", ["who"]),
    s("Sizning ismingiz nima?", "What is your name?", ["you"]),
    s("Uning (yigitning) sevimli rangi ko'k.", "His favourite colour is blue.", ["him"], ["His favorite color is blue.", "His favorite colour is blue.", "His favourite color is blue."]),
    s("Itimizning ismi Rex.", "Our dog's name is Rex.", ["dog"]),
    s("Bu kimning ruchkasi? Meniki.", "Whose pen is this? It's mine.", ["my"], ["Whose pen is this? It is mine."]),
    s("Sardorning singlisi mening do'stim.", "Sardor's sister is my friend.", ["me"], ["Sardor's little sister is my friend.", "Sardor's younger sister is my friend."]),
    s("Ularning bolalari maktabda.", "Their children are at school.", ["there"], ["Their kids are at school."]),
    s("Mening telefonim yangi, seniki esa eski.", "My phone is new, but yours is old.", ["your"], ["My phone is new and yours is old."]),
    s("Bu Malikaning daftari emas, Zarinaniki.", "This isn't Malika's notebook, it's Zarina's.", ["Zarina"]),
  ],
  test: [
    s("Bu mening ruchkam.", "This is my pen.", ["me"]),
    s("Uning (qizning) sochi uzun.", "Her hair is long.", ["she"]),
    s("Uning (yigitning) akasi o'qituvchi.", "His brother is a teacher.", ["he"], ["His older brother is a teacher."]),
    s("Bizning sinfimiz katta.", "Our class is big.", ["we"], ["Our classroom is big."]),
    s("Ularning mashinasi yangi.", "Their car is new.", ["they"]),
    s("Sizning xonangiz juda chiroyli.", "Your room is very beautiful.", ["you"], ["Your room is very nice."]),
    s("Alining otasi shifokor.", "Ali's father is a doctor.", ["Ali"], ["Ali's dad is a doctor."]),
    s("Singlimning ismi Sevara.", "My sister's name is Sevara.", ["sister"], ["My little sister's name is Sevara.", "My younger sister's name is Sevara."]),
    s("Bu Kamolaning sumkasi.", "This is Kamola's bag.", ["Kamola"]),
    s("Ota-onamning mashinasi oq.", "My parents' car is white.", ["parent"]),
    s("Bu daftar meniki.", "This notebook is mine.", ["my"]),
    s("Bu uy ularniki.", "This house is theirs.", ["their"]),
    s("Bu kitoblar bizniki.", "These books are ours.", ["our"]),
    s("Bu telefon sizniki emasmi?", "Isn't this phone yours?", ["your"], ["Is this phone not yours?"]),
    s("Bu kimning mashinasi?", "Whose car is this?", ["who's"]),
    s("Bu kimning kalitlari?", "Whose keys are these?", ["who"]),
    s("It kichkina. Uning dumi oq.", "The dog is small. Its tail is white.", ["it's"]),
    s("Bu kimning kitobi? Madinaniki.", "Whose book is this? It's Madina's.", ["Madina"], ["Whose book is this? It is Madina's."]),
    s("Mening sumkam qora, uniki (qizniki) esa qizil.", "My bag is black, but hers is red.", ["her"], ["My bag is black and hers is red."]),
    s("Bu bizning o'qituvchimizning stoli.", "This is our teacher's desk.", ["teacher"], ["This is our teacher's table."]),
  ],
};

/* ───────────────────────────── 5. Pronouns ───────────────────────────── */

const PRONOUNS: GrammarTopicContent = {
  slug: "a1-pronouns",
  level: "A1",
  position: 5,
  title: { en: "Pronouns (I / me, he / him)", uz: "Olmoshlar (I / me, he / him)" },
  explanation: {
    uz: [
      "Gapda harakat qiluvchi (ega) uchun: I, you, he, she, it, we, they.",
      "Fe'ldan yoki predlogdan keyin (to'ldiruvchi) uchun: me, you, him, her, it, us, them.",
      "I love her = Men uni yaxshi ko'raman. She loves me = U meni yaxshi ko'radi.",
      "Predlogdan keyin ham me, him, her, us, them: with me (men bilan), for them (ular uchun).",
      "O'zbek tilida \"u\" bitta, ingliz tilida esa: he (erkak), she (ayol), it (narsa, hayvon).",
    ].join("\n"),
    pattern: "subject: I / you / he / she / it / we / they · object: me / you / him / her / it / us / them",
    examples: [
      { en: "I know him.", uz: "Men uni (yigitni) taniyman." },
      { en: "She helps us.", uz: "U (qiz) bizga yordam beradi." },
      { en: "Come with me.", uz: "Men bilan yur." },
      { en: "This present is for them.", uz: "Bu sovg'a ular uchun." },
    ],
  },
  build: [
    s("Men uni (yigitni) taniyman.", "I know him.", ["he"]),
    s("U (qiz) meni taniydi.", "She knows me.", ["I"]),
    s("Biz ularni yaxshi ko'ramiz.", "We love them.", ["they"], ["We like them."]),
    s("Ular bizga yordam beradi.", "They help us.", ["we"]),
    s("Men bilan yur.", "Come with me.", ["I"]),
    s("Bu sovg'a sen uchun.", "This present is for you.", ["your"], ["This gift is for you."]),
    s("Ali qayerda? Men uni ko'rmayapman.", "Where is Ali? I can't see him.", ["he"]),
    s("Madina qayerda? Men uni qidiryapman.", "Where is Madina? I'm looking for her.", ["she"]),
    s("Bu kitob juda qiziq. Men uni yaxshi ko'raman.", "This book is very interesting. I love it.", ["its"], ["This book is very interesting. I like it."]),
    s("Ota-onam menga har kuni qo'ng'iroq qilishadi.", "My parents call me every day.", ["I"]),
    s("O'qituvchi bizga savol beradi.", "The teacher asks us a question.", ["we"]),
    s("Iltimos, menga ruchkangni ber.", "Please give me your pen.", ["I"], ["Give me your pen, please."]),
    s("Biz ular bilan futbol o'ynaymiz.", "We play football with them.", ["they"], ["We play soccer with them."]),
    s("U (yigit) menga har kuni xat yozadi.", "He writes to me every day.", ["I"]),
    s("Sardor va men do'stmiz.", "Sardor and I are friends.", ["me"]),
    s("Malika ularga ingliz tilini o'rgatadi.", "Malika teaches them English.", ["they"]),
    s("Mana sening choying. Uni ich.", "Here is your tea. Drink it.", ["its"]),
    s("Uni (qizni) taniysanmi?", "Do you know her?", ["she"]),
    s("U (qiz) uni (yigitni) yaxshi ko'radi.", "She loves him.", ["he"], ["She likes him."]),
    s("Ular bizni kutishyapti.", "They are waiting for us.", ["we"]),
    s("Iltimos, bizga qo'ng'iroq qiling.", "Please call us.", ["we"], ["Call us, please."]),
    s("Akam bizni maktabga olib boradi.", "My brother takes us to school.", ["we"], ["My older brother takes us to school."]),
    s("Men u bilan (qiz bilan) gaplashmoqchiman.", "I want to talk to her.", ["she"], ["I want to speak to her.", "I want to talk with her."]),
    s("U (yigit) biz bilan yashaydi.", "He lives with us.", ["we"]),
    s("Bu gullar ular uchun.", "These flowers are for them.", ["they"]),
    s("Menga qara!", "Look at me!", ["I"]),
    s("Sen va men bir sinfdamiz.", "You and I are in the same class.", ["me"]),
    s("Ular meni tushunishmaydi.", "They don't understand me.", ["I"]),
    s("Biz uni (yigitni) maktabda ko'ramiz.", "We see him at school.", ["he"]),
    s("Kamola va Zarina qayerda? Men ularni topa olmayapman.", "Where are Kamola and Zarina? I can't find them.", ["they"]),
  ],
  test: [
    s("Men uni (qizni) taniyman.", "I know her.", ["she"]),
    s("U (yigit) bizni taniydi.", "He knows us.", ["we"]),
    s("Ular menga yordam beradi.", "They help me.", ["I"]),
    s("Biz ular bilan gaplashamiz.", "We talk to them.", ["they"], ["We talk with them.", "We speak to them."]),
    s("Bu xat sen uchun.", "This letter is for you.", ["your"]),
    s("U bilan (yigit bilan) bor.", "Go with him.", ["he"]),
    s("Bu film juda yaxshi. Men uni yaxshi ko'raman.", "This film is very good. I love it.", ["its"], [
      "This movie is very good. I love it.",
      "This film is very good. I like it.",
      "This movie is very good. I like it.",
    ]),
    s("O'qituvchimiz bizni yaxshi ko'radi.", "Our teacher loves us.", ["we"], ["Our teacher likes us."]),
    s("Madina va men opa-singilmiz.", "Madina and I are sisters.", ["me"]),
    s("Uni (yigitni) taniysizmi?", "Do you know him?", ["he"]),
    s("Iltimos, bizga yordam bering.", "Please help us.", ["we"], ["Help us, please."]),
    s("Ular bizni kutishmayapti.", "They aren't waiting for us.", ["we"]),
    s("Men har kuni unga (qizga) qo'ng'iroq qilaman.", "I call her every day.", ["she"]),
    s("Ali qayerda? Biz uni kutyapmiz.", "Where is Ali? We are waiting for him.", ["he"]),
    s("Menga suv bering.", "Give me water.", ["I"], ["Give me some water.", "Give me water, please.", "Please give me water."]),
    s("Ular biz bilan yashamaydi.", "They don't live with us.", ["we"]),
    s("Bu kitoblar ular uchun emas.", "These books aren't for them.", ["they"]),
    s("U (qiz) men bilan maktabga boradi.", "She goes to school with me.", ["I"]),
    s("Mana sening kaliting. Uni yo'qotma.", "Here is your key. Don't lose it.", ["its"]),
    s("Jasur va men futbol o'ynaymiz.", "Jasur and I play football.", ["me"], ["Jasur and I play soccer."]),
  ],
};

/* ───────────────────────────── 6. There is / are ───────────────────────────── */

const THERE_IS: GrammarTopicContent = {
  slug: "a1-there-is-are",
  level: "A1",
  position: 6,
  title: { en: "There is / There are", uz: "There is / there are (... bor)" },
  explanation: {
    uz: [
      "There is / there are biror joyda nimadir \"bor\"ligini aytadi: Xonada stol bor = There is a table in the room.",
      "Bitta narsa bilan there is (there's): There is a shop near my house.",
      "Ko'plik bilan there are: There are three books on the desk.",
      "Inkor: there isn't / there aren't (\"... yo'q\"): There isn't a park here. There aren't any shops.",
      "So'roq: Is there …? / Are there …? Qisqa javob: Yes, there is. / No, there aren't.",
      "Diqqat: \"... bor\" degani har doim have got emas! Joy haqida gapirsak - there is / are.",
    ].join("\n"),
    pattern: "There is + a / an + noun · There are + plural noun · not: there isn't / there aren't · question: Is there …? / Are there …?",
    examples: [
      { en: "There is a cat in the garden.", uz: "Bog'da mushuk bor." },
      { en: "There are two banks in our street.", uz: "Bizning ko'chada ikkita bank bor." },
      { en: "There isn't a hospital in the village.", uz: "Qishloqda kasalxona yo'q." },
      { en: "Is there a bus stop near here?", uz: "Bu yerga yaqin avtobus bekati bormi?" },
    ],
  },
  build: [
    s("Xonada stol bor.", "There is a table in the room.", ["are"]),
    s("Bog'da mushuk bor.", "There is a cat in the garden.", ["are"]),
    s("Stol ustida uchta kitob bor.", "There are three books on the table.", ["is"], ["There are three books on the desk."]),
    s("Sinfimizda yigirmata o'quvchi bor.", "There are twenty students in our class.", ["is"], ["There are twenty pupils in our class."]),
    s("Uyimiz yonida do'kon bor.", "There is a shop near our house.", ["are"], ["There is a shop next to our house.", "There's a shop near our house."]),
    s("Muzlatgichda sut bor.", "There is milk in the fridge.", ["are"], ["There is some milk in the fridge."]),
    s("Shaharda ko'plab parklar bor.", "There are many parks in the city.", ["is"], ["There are a lot of parks in the city.", "There are lots of parks in the city."]),
    s("Devorda rasm bor.", "There is a picture on the wall.", ["are"]),
    s("Bu ko'chada ikkita bank bor.", "There are two banks in this street.", ["is"], ["There are two banks on this street."]),
    s("Sumkamda olma bor.", "There is an apple in my bag.", ["are", "a"]),
    s("Bu yerda bank yo'q.", "There isn't a bank here.", ["aren't"]),
    s("Qishloqda kasalxona yo'q.", "There isn't a hospital in the village.", ["aren't"]),
    s("Parkda odamlar yo'q.", "There aren't any people in the park.", ["isn't"], ["There aren't people in the park."]),
    s("Muzlatgichda tuxum yo'q.", "There aren't any eggs in the fridge.", ["isn't"], ["There aren't eggs in the fridge."]),
    s("Xonada televizor yo'q.", "There isn't a TV in the room.", ["aren't"], ["There isn't a television in the room."]),
    s("Bu shaharda metro yo'q.", "There isn't a metro in this city.", ["aren't"], ["There isn't a subway in this city."]),
    s("Stol ustida stakanlar yo'q.", "There aren't any glasses on the table.", ["isn't"], ["There aren't glasses on the table."]),
    s("Bu yerga yaqin avtobus bekati bormi?", "Is there a bus stop near here?", ["are"]),
    s("Mehmonxonada basseyn bormi?", "Is there a pool in the hotel?", ["are"], ["Is there a swimming pool in the hotel?"]),
    s("Sinfda kompyuterlar bormi?", "Are there any computers in the classroom?", ["is"], ["Are there computers in the classroom?"]),
    s("Bu ko'chada restoranlar bormi?", "Are there any restaurants in this street?", ["is"], [
      "Are there restaurants in this street?",
      "Are there any restaurants on this street?",
      "Are there restaurants on this street?",
    ]),
    s("Sumkangda ruchka bormi?", "Is there a pen in your bag?", ["are"]),
    s("Bog'da daraxtlar bormi? Ha, bor.", "Are there trees in the garden? Yes, there are.", ["is"], [
      "Are there any trees in the garden? Yes, there are.",
    ]),
    s("Bu yerda dorixona bormi? Yo'q, yo'q.", "Is there a pharmacy here? No, there isn't.", ["aren't"]),
    s("Xonamda karavot va ikkita stul bor.", "There is a bed and two chairs in my room.", ["have"], ["There's a bed and two chairs in my room."]),
    s("Uyimizda to'rtta xona bor.", "There are four rooms in our house.", ["is"]),
    s("Bir haftada yetti kun bor.", "There are seven days in a week.", ["is"]),
    s("Shkafda nima bor?", "What is there in the cupboard?", ["are"], ["What's in the cupboard?", "What is in the cupboard?"]),
    s("Sinfingizda nechta o'quvchi bor?", "How many students are there in your class?", ["is"], ["How many pupils are there in your class?"]),
    s("Bu yerda kafe bor, lekin restoran yo'q.", "There is a cafe here, but there isn't a restaurant.", ["aren't"]),
  ],
  test: [
    s("Bog'da it bor.", "There is a dog in the garden.", ["are"], ["There's a dog in the garden."]),
    s("Stol ustida ikkita stakan bor.", "There are two glasses on the table.", ["is"], ["There are two cups on the table."]),
    s("Uyim yonida park bor.", "There is a park near my house.", ["are"], ["There's a park near my house.", "There is a park next to my house."]),
    s("Sinfimizda o'n beshta o'quvchi bor.", "There are fifteen students in our class.", ["is"], ["There are fifteen pupils in our class."]),
    s("Choynakda choy bor.", "There is tea in the teapot.", ["are"], ["There is some tea in the teapot."]),
    s("Samarqandda ko'plab muzeylar bor.", "There are many museums in Samarkand.", ["is"], ["There are a lot of museums in Samarkand.", "There are lots of museums in Samarkand."]),
    s("Bu yerda supermarket yo'q.", "There isn't a supermarket here.", ["aren't"]),
    s("Ko'chada mashinalar yo'q.", "There aren't any cars in the street.", ["isn't"], [
      "There aren't cars in the street.",
      "There aren't any cars on the street.",
      "There aren't cars on the street.",
    ]),
    s("Xonada deraza yo'q.", "There isn't a window in the room.", ["aren't"]),
    s("Sumkamda kitoblar yo'q.", "There aren't any books in my bag.", ["isn't"], ["There aren't books in my bag."]),
    s("Bu yerga yaqin bank bormi?", "Is there a bank near here?", ["are"]),
    s("Muzlatgichda olmalar bormi?", "Are there any apples in the fridge?", ["is"], ["Are there apples in the fridge?"]),
    s("Xonangda kompyuter bormi?", "Is there a computer in your room?", ["are"]),
    s("Parkda bolalar bormi?", "Are there any children in the park?", ["is"], ["Are there children in the park?", "Are there any kids in the park?", "Are there kids in the park?"]),
    s("Bu yerda kafe bormi? Ha, bor.", "Is there a cafe here? Yes, there is.", ["are"]),
    s("Shkafda ko'ylaklar bormi? Yo'q, yo'q.", "Are there any shirts in the wardrobe? No, there aren't.", ["isn't"], [
      "Are there shirts in the wardrobe? No, there aren't.",
      "Are there any dresses in the wardrobe? No, there aren't.",
      "Are there dresses in the wardrobe? No, there aren't.",
    ]),
    s("Bir yilda o'n ikki oy bor.", "There are twelve months in a year.", ["is"]),
    s("Oilangizda necha kishi bor?", "How many people are there in your family?", ["is"]),
    s("Xonamda stol bor, lekin stul yo'q.", "There is a desk in my room, but there isn't a chair.", ["aren't"], [
      "There is a table in my room, but there isn't a chair.",
      "There's a desk in my room, but there isn't a chair.",
      "There's a table in my room, but there isn't a chair.",
    ]),
    s("Bizning shaharda universitet bor.", "There is a university in our city.", ["are"], ["There's a university in our city.", "There is a university in our town."]),
  ],
};

/* ───────────────────────────── 7. Present Simple ───────────────────────────── */

const PRESENT_SIMPLE: GrammarTopicContent = {
  slug: "a1-present-simple",
  level: "A1",
  position: 7,
  title: { en: "Present Simple", uz: "Present Simple (odatiy hozirgi zamon)" },
  explanation: {
    uz: [
      "Present Simple odat, takrorlanadigan ish va doimiy faktlar uchun: I drink tea every morning. Water boils at 100 degrees.",
      "He, she, it bilan fe'lga -s / -es qo'shiladi: she works, he watches, it goes. Have esa has bo'ladi.",
      "Inkor: don't / doesn't + fe'l: I don't like coffee. She doesn't work (works emas!).",
      "So'roq: Do / Does + ega + fe'l: Do you speak English? Does Ali live here?",
      "Qisqa javob: Yes, I do. / No, he doesn't.",
      "Ko'p ishlatiladigan so'zlar: always, usually, often, sometimes, never, every day, on Mondays.",
    ].join("\n"),
    pattern: "I / you / we / they + verb | he / she / it + verb-s · not: don't / doesn't + verb · question: Do / Does + subject + verb …?",
    examples: [
      { en: "I drink tea every morning.", uz: "Men har kuni ertalab choy ichaman." },
      { en: "Madina works in a bank.", uz: "Madina bankda ishlaydi." },
      { en: "He doesn't like coffee.", uz: "U qahvani yoqtirmaydi." },
      { en: "Do you speak English?", uz: "Siz ingliz tilida gaplashasizmi?" },
    ],
  },
  build: [
    s("Men har kuni ertalab choy ichaman.", "I drink tea every morning.", ["drinks"]),
    s("Madina bankda ishlaydi.", "Madina works in a bank.", ["work"], ["Madina works at a bank."]),
    s("Biz Toshkentda yashaymiz.", "We live in Tashkent.", ["lives"]),
    s("Ali har kuni futbol o'ynaydi.", "Ali plays football every day.", ["play"], ["Ali plays soccer every day."]),
    s("Ular ingliz tilini o'rganishadi.", "They learn English.", ["learns"], ["They study English."]),
    s("Akam universitetda o'qiydi.", "My brother studies at university.", ["study"], ["My older brother studies at university.", "My brother studies at a university."]),
    s("Dars soat sakkizda boshlanadi.", "The lesson starts at eight o'clock.", ["start"], ["The lesson begins at eight o'clock.", "The lesson starts at eight.", "The lesson begins at eight."]),
    s("Onam har kuni ovqat pishiradi.", "My mother cooks every day.", ["cook"], ["My mom cooks every day.", "My mum cooks every day."]),
    s("U (yigit) kechqurun televizor ko'radi.", "He watches TV in the evening.", ["watch"]),
    s("Malika har doim avtobusda boradi.", "Malika always goes by bus.", ["go"]),
    s("Men qahvani yoqtirmayman.", "I don't like coffee.", ["doesn't"]),
    s("Sardor go'sht yemaydi.", "Sardor doesn't eat meat.", ["don't"]),
    s("Biz yakshanba kuni ishlamaymiz.", "We don't work on Sunday.", ["doesn't"], ["We don't work on Sundays."]),
    s("Otam chekmaydi.", "My father doesn't smoke.", ["smokes"], ["My dad doesn't smoke."]),
    s("Ular Samarqandda yashashmaydi.", "They don't live in Samarkand.", ["doesn't"]),
    s("Zarina hech qachon kech qolmaydi.", "Zarina is never late.", ["are"]),
    s("Mening mushugim sutni yoqtirmaydi.", "My cat doesn't like milk.", ["likes"]),
    s("Siz ingliz tilida gaplashasizmi?", "Do you speak English?", ["does"]),
    s("Ali shu yerda yashaydimi?", "Does Ali live here?", ["lives"]),
    s("Ular qayerda ishlaydi?", "Where do they work?", ["does"]),
    s("Avtobus soat nechada keladi?", "What time does the bus come?", ["comes"], ["What time does the bus arrive?", "When does the bus come?", "When does the bus arrive?"]),
    s("Siz qahva ichasizmi? Yo'q, ichmayman.", "Do you drink coffee? No, I don't.", ["does"]),
    s("Madina gitara chaladimi? Ha, chaladi.", "Does Madina play the guitar? Yes, she does.", ["do"], ["Does Madina play guitar? Yes, she does."]),
    s("Sen har kuni sport bilan shug'ullanasanmi?", "Do you do sport every day?", ["does"], ["Do you do sports every day?", "Do you exercise every day?"]),
    s("Men odatda soat yettida turaman.", "I usually get up at seven o'clock.", ["gets"], ["I usually get up at seven.", "I usually wake up at seven o'clock.", "I usually wake up at seven."]),
    s("U (qiz) ba'zan kitob o'qiydi.", "She sometimes reads books.", ["read"], ["Sometimes she reads books."]),
    s("Biz tez-tez kinoga boramiz.", "We often go to the cinema.", ["goes"], ["We often go to the movies."]),
    s("Jasur hech qachon nonushta qilmaydi.", "Jasur never has breakfast.", ["have"], ["Jasur never eats breakfast."]),
    s("Suv yuz darajada qaynaydi.", "Water boils at 100 degrees.", ["boil"], ["Water boils at a hundred degrees.", "Water boils at one hundred degrees."]),
    s("Men choyni yaxshi ko'raman, lekin akam qahvani yaxshi ko'radi.", "I like tea, but my brother likes coffee.", ["liking"], ["I love tea, but my brother loves coffee."]),
  ],
  test: [
    s("Men maktabga piyoda boraman.", "I walk to school.", ["walks"], ["I go to school on foot."]),
    s("Kamola kasalxonada ishlaydi.", "Kamola works in a hospital.", ["work"], ["Kamola works at a hospital."]),
    s("Ular har kuni ingliz tilini o'rganishadi.", "They study English every day.", ["studies"], ["They learn English every day."]),
    s("Otam gazeta o'qiydi.", "My father reads the newspaper.", ["read"], ["My dad reads the newspaper.", "My father reads newspapers.", "My dad reads newspapers."]),
    s("Do'kon soat to'qqizda ochiladi.", "The shop opens at nine o'clock.", ["open"], ["The shop opens at nine.", "The store opens at nine o'clock.", "The store opens at nine."]),
    s("Biz har yakshanba buvimiznikiga boramiz.", "We visit our grandmother every Sunday.", ["visits"], ["We visit our grandma every Sunday."]),
    s("Men baliqni yoqtirmayman.", "I don't like fish.", ["doesn't"]),
    s("Ali shanba kuni ishlamaydi.", "Ali doesn't work on Saturday.", ["don't"], ["Ali doesn't work on Saturdays."]),
    s("Ular televizor ko'rishmaydi.", "They don't watch TV.", ["doesn't"]),
    s("Singlim qahva ichmaydi.", "My sister doesn't drink coffee.", ["drinks"], ["My little sister doesn't drink coffee.", "My younger sister doesn't drink coffee."]),
    s("Siz shu yerda yashaysizmi?", "Do you live here?", ["does"]),
    s("Malika ingliz tilida gaplashadimi?", "Does Malika speak English?", ["speaks"]),
    s("Sen qayerda ishlaysan?", "Where do you work?", ["does"]),
    s("Film soat nechada boshlanadi?", "What time does the film start?", ["starts"], [
      "What time does the movie start?",
      "When does the film start?",
      "When does the movie start?",
      "What time does the film begin?",
      "What time does the movie begin?",
    ]),
    s("Akang futbol o'ynaydimi? Ha, o'ynaydi.", "Does your brother play football? Yes, he does.", ["do"], ["Does your brother play soccer? Yes, he does."]),
    s("Siz choy ichasizmi? Ha, ichaman.", "Do you drink tea? Yes, I do.", ["does"]),
    s("U (yigit) har doim kech qoladi.", "He is always late.", ["are"]),
    s("Biz odatda uyda tushlik qilamiz.", "We usually have lunch at home.", ["has"], ["We usually eat lunch at home."]),
    s("Zarina hech qachon go'sht yemaydi.", "Zarina never eats meat.", ["eat"]),
    s("Men ingliz tilini o'rganaman, lekin Sardor rus tilini o'rganadi.", "I learn English, but Sardor learns Russian.", ["learning"], [
      "I study English, but Sardor studies Russian.",
      "I learn English and Sardor learns Russian.",
      "I study English and Sardor studies Russian.",
    ]),
  ],
};

/* ───────────────────────────── 8. Present Continuous ───────────────────────────── */

const PRESENT_CONTINUOUS: GrammarTopicContent = {
  slug: "a1-present-continuous",
  level: "A1",
  position: 8,
  title: { en: "Present Continuous", uz: "Present Continuous (hozir bo'layotgan ish)" },
  explanation: {
    uz: [
      "Present Continuous hozir, gapirayotgan paytda bo'layotgan ish uchun: I am reading now = Men hozir o'qiyapman.",
      "Tuzilishi: am / is / are + fe'l-ing: She is cooking. They are playing.",
      "Inkor: am not / isn't / aren't + fe'l-ing: He isn't sleeping.",
      "So'roq: Am / Is / Are + ega + fe'l-ing: Are you listening? What is Ali doing?",
      "-ing qo'shish: write - writing (e tushib qoladi), swim - swimming, run - running, sit - sitting.",
      "Ko'p ishlatiladigan so'zlar: now, right now, at the moment, today, Look!, Listen!",
      "Present Simple bilan farqi: I work in a bank (doim). I am working now (hozir).",
    ].join("\n"),
    pattern: "am / is / are + verb-ing · not: am not / isn't / aren't + verb-ing · question: Am / Is / Are + subject + verb-ing …?",
    examples: [
      { en: "I am reading a book now.", uz: "Men hozir kitob o'qiyapman." },
      { en: "Madina is cooking dinner.", uz: "Madina kechki ovqat pishiryapti." },
      { en: "They aren't sleeping.", uz: "Ular uxlashmayapti." },
      { en: "What are you doing?", uz: "Nima qilyapsan?" },
    ],
  },
  build: [
    s("Men hozir kitob o'qiyapman.", "I am reading a book now.", ["read"], ["I am reading a book right now.", "Now I am reading a book."]),
    s("Madina kechki ovqat pishiryapti.", "Madina is cooking dinner.", ["are"]),
    s("Bolalar bog'da o'ynashyapti.", "The children are playing in the garden.", ["is"], ["The kids are playing in the garden."]),
    s("Otam mashina haydayapti.", "My father is driving.", ["drives"], ["My dad is driving."]),
    s("Biz ingliz tilini o'rganyapmiz.", "We are learning English.", ["learn"], ["We are studying English."]),
    s("Qara! Yomg'ir yog'yapti.", "Look! It is raining.", ["rains"]),
    s("Ali telefonda gaplashyapti.", "Ali is talking on the phone.", ["talks"], ["Ali is speaking on the phone."]),
    s("Men seni kutyapman.", "I am waiting for you.", ["wait"]),
    s("Ular televizor ko'rishyapti.", "They are watching TV.", ["watches"]),
    s("Malika xat yozyapti.", "Malika is writing a letter.", ["writeing"]),
    s("Bolalar basseynda suzishyapti.", "The children are swimming in the pool.", ["swiming"], ["The kids are swimming in the pool."]),
    s("Men uxlamayapman.", "I'm not sleeping.", ["don't"]),
    s("Sardor ishlamayapti, u dam olyapti.", "Sardor isn't working, he is resting.", ["doesn't"]),
    s("Biz hozir ovqatlanmayapmiz.", "We aren't eating now.", ["don't"], ["We aren't eating right now."]),
    s("Ular o'qituvchini tinglashmayapti.", "They aren't listening to the teacher.", ["don't"]),
    s("Quyosh charaqlamayapti.", "The sun isn't shining.", ["doesn't"]),
    s("Nima qilyapsan?", "What are you doing?", ["do"]),
    s("Ali nima qilyapti?", "What is Ali doing?", ["does"]),
    s("Sen meni tinglayapsanmi?", "Are you listening to me?", ["do"]),
    s("Madina uxlayaptimi?", "Is Madina sleeping?", ["does"]),
    s("Qayerga ketyapsiz?", "Where are you going?", ["do"]),
    s("Nega yig'layapsan?", "Why are you crying?", ["cry"]),
    s("Ular futbol o'ynashyaptimi? Ha, o'ynashyapti.", "Are they playing football? Yes, they are.", ["do"], ["Are they playing soccer? Yes, they are."]),
    s("Jasur uy vazifasini qilyaptimi? Yo'q.", "Is Jasur doing his homework? No, he isn't.", ["does"]),
    s("Hozir men stulda o'tiribman.", "I am sitting on a chair now.", ["siting"], ["Now I am sitting on a chair."]),
    s("Eshit! Kimdir qo'shiq aytyapti.", "Listen! Somebody is singing.", ["sings"], ["Listen! Someone is singing."]),
    s("Men odatda choy ichaman, lekin bugun qahva ichyapman.", "I usually drink tea, but today I'm drinking coffee.", ["drinks"]),
    s("Onam bankda ishlaydi, lekin hozir u uyda.", "My mother works in a bank, but now she is at home.", ["working"], [
      "My mom works in a bank, but now she is at home.",
      "My mum works in a bank, but now she is at home.",
    ]),
    s("Biz hozir avtobusni kutyapmiz.", "We are waiting for the bus now.", ["wait"], ["We are waiting for the bus right now.", "Now we are waiting for the bus."]),
    s("Akam bu oy Londonda ishlayapti.", "My brother is working in London this month.", ["works"], ["My older brother is working in London this month."]),
  ],
  test: [
    s("Men hozir ovqat pishiryapman.", "I am cooking now.", ["cook"], ["I am cooking right now.", "Now I am cooking."]),
    s("Zarina musiqa tinglayapti.", "Zarina is listening to music.", ["listens"]),
    s("Bolalar parkda yugurishyapti.", "The children are running in the park.", ["runing"], ["The kids are running in the park."]),
    s("Onam choy ichyapti.", "My mother is drinking tea.", ["drinks"], ["My mom is drinking tea.", "My mum is drinking tea."]),
    s("Qara! Qor yog'yapti.", "Look! It is snowing.", ["snows"]),
    s("Biz uy vazifasini qilyapmiz.", "We are doing our homework.", ["do"], ["We are doing homework."]),
    s("Men televizor ko'rmayapman.", "I'm not watching TV.", ["don't"]),
    s("Ali uxlamayapti, u kitob o'qiyapti.", "Ali isn't sleeping, he is reading a book.", ["doesn't"]),
    s("Ular hozir ishlashmayapti.", "They aren't working now.", ["don't"], ["They aren't working right now."]),
    s("Malika gaplashmayapti.", "Malika isn't talking.", ["doesn't"], ["Malika isn't speaking."]),
    s("Sen nima o'qiyapsan?", "What are you reading?", ["do"]),
    s("Sardor qayerga ketyapti?", "Where is Sardor going?", ["does"]),
    s("Ular nima qilishyapti?", "What are they doing?", ["do"]),
    s("Yomg'ir yog'yaptimi?", "Is it raining?", ["does"]),
    s("Sen meni kutyapsanmi? Ha.", "Are you waiting for me? Yes, I am.", ["do"]),
    s("Madina ovqat pishiryaptimi? Yo'q.", "Is Madina cooking? No, she isn't.", ["does"]),
    s("Eshit! Chaqaloq yig'layapti.", "Listen! The baby is crying.", ["cries"]),
    s("Biz hozir stol atrofida o'tiribmiz.", "We are sitting at the table now.", ["siting"], ["Now we are sitting at the table.", "We are sitting at the table right now."]),
    s("Otam odatda mashinada boradi, lekin bugun piyoda ketyapti.", "My father usually drives, but today he is walking.", ["walks"], [
      "My dad usually drives, but today he is walking.",
    ]),
    s("Jasur va Timur hozir futbol o'ynashyapti.", "Jasur and Timur are playing football now.", ["is"], [
      "Jasur and Timur are playing soccer now.",
      "Timur and Jasur are playing football now.",
      "Jasur and Timur are playing football right now.",
    ]),
  ],
};

/* ───────────────────────────── 9. Basic modals ───────────────────────────── */

const MODALS: GrammarTopicContent = {
  slug: "a1-modals",
  level: "A1",
  position: 9,
  title: { en: "Modals: must, should, have to", uz: "Modal fe'llar: must, should, have to" },
  explanation: {
    uz: [
      "Must - \"... shart, ... kerak\" (qoida yoki o'zingiz muhim deb bilgan narsa): You must wear a seatbelt.",
      "Mustn't - \"... mumkin emas, ... taqiqlangan\": You mustn't smoke here.",
      "Should / shouldn't - maslahat: \"... kerak / ... yaxshi bo'lardi\": You should see a doctor.",
      "Have to / has to - \"... majburman\" (tashqi sabab): I have to work on Saturday. She has to wear a uniform.",
      "Don't have to - \"... shart emas\" (mustn't emas!): You don't have to come = Kelishing shart emas.",
      "Must, should dan keyin fe'l oddiy shaklda, to qo'shilmaydi: She must go (to go emas, goes emas).",
    ].join("\n"),
    pattern: "must / mustn't + verb · should / shouldn't + verb · have to / has to + verb · don't / doesn't have to + verb",
    examples: [
      { en: "You must stop at a red light.", uz: "Qizil chiroqda to'xtash shart." },
      { en: "You shouldn't eat so much sugar.", uz: "Shuncha ko'p shakar yemasligingiz kerak." },
      { en: "I have to get up early.", uz: "Men erta turishim kerak." },
      { en: "You don't have to pay.", uz: "To'lashingiz shart emas." },
    ],
  },
  build: [
    s("Siz xavfsizlik kamarini taqishingiz shart.", "You must wear a seatbelt.", ["to"]),
    s("Qizil chiroqda to'xtash shart.", "You must stop at a red light.", ["stops"]),
    s("Men bugun uy vazifasini tugatishim kerak.", "I must finish my homework today.", ["to"], ["I must finish my homework tonight.", "Today I must finish my homework."]),
    s("Bu yerda chekish mumkin emas.", "You mustn't smoke here.", ["smoking"]),
    s("Muzeyda rasmga olish mumkin emas.", "You mustn't take photos in the museum.", ["to"], ["You mustn't take pictures in the museum."]),
    s("Imtihonda gaplashish mumkin emas.", "You mustn't talk in the exam.", ["talking"], ["You mustn't talk during the exam."]),
    s("Siz shifokorga borishingiz kerak.", "You should see a doctor.", ["to"], ["You should go to the doctor.", "You should go to a doctor."]),
    s("Ko'proq suv ichishing kerak.", "You should drink more water.", ["drinks"]),
    s("Ko'p shakar yemasligingiz kerak.", "You shouldn't eat a lot of sugar.", ["to"], ["You shouldn't eat much sugar.", "You shouldn't eat lots of sugar."]),
    s("Biz erta uxlashimiz kerak.", "We should go to bed early.", ["going"]),
    s("Kech qolmasligingiz kerak.", "You shouldn't be late.", ["are"]),
    s("Sardor ko'proq o'qishi kerak.", "Sardor should study more.", ["studies"]),
    s("Men shanba kuni ishlashim kerak.", "I have to work on Saturday.", ["has"], ["I have to work on Saturdays."]),
    s("Madina maktab formasini kiyishi kerak.", "Madina has to wear a uniform.", ["have"], ["Madina has to wear a school uniform."]),
    s("Biz soat oltida turishimiz kerak.", "We have to get up at six o'clock.", ["has"], ["We have to get up at six.", "We have to wake up at six o'clock.", "We have to wake up at six."]),
    s("Otam har kuni ishga borishi kerak.", "My father has to go to work every day.", ["have"], ["My dad has to go to work every day."]),
    s("Ertaga maktabga borishing shart emas.", "You don't have to go to school tomorrow.", ["mustn't"], ["Tomorrow you don't have to go to school."]),
    s("Ali ishlashi shart emas.", "Ali doesn't have to work.", ["don't"]),
    s("Bu yerda to'lash shart emas.", "You don't have to pay here.", ["doesn't"]),
    s("Biz forma kiyishimiz shart emas.", "We don't have to wear a uniform.", ["doesn't"]),
    s("Men nima qilishim kerak?", "What should I do?", ["to"]),
    s("Men bu kitobni o'qishim kerakmi?", "Should I read this book?", ["to"]),
    s("Biz ertaga kelishimiz kerakmi?", "Do we have to come tomorrow?", ["does"], ["Tomorrow do we have to come?"]),
    s("Malika ertaga ishlashi kerakmi?", "Does Malika have to work tomorrow?", ["has"]),
    s("Kutubxonada shovqin qilish mumkin emas.", "You mustn't make noise in the library.", ["to"], ["You mustn't make a noise in the library."]),
    s("Sen ota-onangga yordam berishing kerak.", "You should help your parents.", ["helps"]),
    s("Men endi ketishim kerak.", "I have to go now.", ["has"], ["I must go now."]),
    s("Har kuni sport bilan shug'ullanishimiz kerak.", "We should do sport every day.", ["to"], ["We should do sports every day.", "We should exercise every day."]),
    s("Ertaga yakshanba, erta turishim shart emas.", "Tomorrow is Sunday, I don't have to get up early.", ["mustn't"], [
      "Tomorrow is Sunday, so I don't have to get up early.",
    ]),
    s("O'qituvchi bilan ingliz tilida gaplashishimiz kerak.", "We have to speak English with the teacher.", ["has"], ["We must speak English with the teacher."]),
  ],
  test: [
    s("Siz pasportingizni ko'rsatishingiz shart.", "You must show your passport.", ["to"]),
    s("Men bugun onamga qo'ng'iroq qilishim kerak.", "I must call my mother today.", ["to"], ["I must call my mom today.", "I must call my mum today.", "Today I must call my mother."]),
    s("Sinfda ovqat yeyish mumkin emas.", "You mustn't eat in class.", ["eating"], ["You mustn't eat in the classroom."]),
    s("Bu suvni ichish mumkin emas.", "You mustn't drink this water.", ["to"]),
    s("Ko'proq meva yeyishingiz kerak.", "You should eat more fruit.", ["eats"]),
    s("Sen dam olishing kerak.", "You should rest.", ["to"], ["You should relax."]),
    s("Ko'p kofe ichmasligingiz kerak.", "You shouldn't drink a lot of coffee.", ["to"], ["You shouldn't drink much coffee.", "You shouldn't drink lots of coffee."]),
    s("Biz kech qolmasligimiz kerak.", "We shouldn't be late.", ["are"]),
    s("Men har kuni ingliz tilini o'rganishim kerak.", "I have to study English every day.", ["has"], ["I have to learn English every day."]),
    s("Kamola ukasiga qarashi kerak.", "Kamola has to look after her brother.", ["have"], ["Kamola has to look after her little brother.", "Kamola has to look after her younger brother."]),
    s("Biz avtobusda borishimiz kerak.", "We have to go by bus.", ["has"], ["We have to take the bus."]),
    s("Bugun ishlashim shart emas.", "I don't have to work today.", ["mustn't"], ["Today I don't have to work."]),
    s("Zarina forma kiyishi shart emas.", "Zarina doesn't have to wear a uniform.", ["don't"]),
    s("Siz kelishingiz shart emas.", "You don't have to come.", ["doesn't"]),
    s("Men nima kiyishim kerak?", "What should I wear?", ["to"]),
    s("Biz chipta sotib olishimiz kerakmi?", "Do we have to buy tickets?", ["does"], ["Do we have to buy a ticket?"]),
    s("Jasur bugun ishlashi kerakmi?", "Does Jasur have to work today?", ["has"]),
    s("Kasalxonada baland ovozda gaplashish mumkin emas.", "You mustn't talk loudly in the hospital.", ["to"], ["You mustn't speak loudly in the hospital."]),
    s("Sen erta uxlashing kerak.", "You should go to bed early.", ["going"]),
    s("Men endi uyga borishim kerak.", "I have to go home now.", ["has"], ["I must go home now."]),
  ],
};

export const A1_PART2_TOPICS: GrammarTopicContent[] = [POSSESSIVES, PRONOUNS, THERE_IS, PRESENT_SIMPLE, PRESENT_CONTINUOUS, MODALS];
