/**
 * A2 (Elementary) grammar — topics 16-20: Passive (Present / Past Simple),
 * Relative clauses, Subject / object questions, So / Neither, Verb patterns.
 * Written by Claude as a DRAFT for teacher review (imported unpublished).
 * APPEND-ONLY: never reorder or delete items once shipped — progress keys on
 * (topic slug, kind, position). Validated by tests/grammar-content.test.ts.
 */
import type { GrammarItemContent, GrammarTopicContent } from "@shared/grammar/types";

/** One sentence: Uzbek prompt, model English, traps, and other correct answers. */
const s = (uz: string, en: string, traps: string[], alt?: string[]): GrammarItemContent =>
  alt ? { uz, en, traps, alt } : { uz, en, traps };

/* ───────────────────────────── 16. Passive ───────────────────────────── */

const PASSIVE: GrammarTopicContent = {
  slug: "a2-passive",
  level: "A2",
  position: 16,
  title: { en: "Passive: Present and Past Simple", uz: "Majhul nisbat (Passive): hozirgi va o'tgan zamon" },
  explanation: {
    uz: [
      "Passive (majhul nisbat) kim qilgani emas, nima qilingani muhim bo'lganda ishlatiladi: The bridge was built in 1990 = Ko'prik 1990-yilda qurilgan.",
      "Present Simple: am / is / are + V3: Cars are made in Japan = Mashinalar Yaponiyada ishlab chiqariladi.",
      "Past Simple: was / were + V3: The house was built in 1950 = Uy 1950-yilda qurilgan.",
      "Kim tomonidan qilinganini by bilan aytamiz: This book was written by Aziz = Bu kitob Aziz tomonidan yozilgan.",
      "Inkor: isn't / aren't / wasn't / weren't + V3: The letter wasn't sent = Xat yuborilmadi.",
      "So'roq: Is / Are / Was / Were + ega + V3? Where was it made? When were these houses built? (did ishlatilmaydi!)",
      "Ko'p uchraydigan V3: make - made, build - built, write - written, sell - sold, speak - spoken, grow - grown, steal - stolen, invent - invented.",
    ].join("\n"),
    pattern: "am / is / are + V3 (present) · was / were + V3 (past) · … by + agent · not: isn't / wasn't + V3 · question: Is / Was + subject + V3 …?",
    examples: [
      { en: "English is spoken in many countries.", uz: "Ingliz tili ko'p mamlakatlarda gapiriladi." },
      { en: "This house was built in 1990.", uz: "Bu uy 1990-yilda qurilgan." },
      { en: "The letters weren't sent.", uz: "Xatlar yuborilmadi." },
      { en: "Where was this phone made?", uz: "Bu telefon qayerda ishlab chiqarilgan?" },
    ],
  },
  build: [
    s("Ingliz tili ko'p mamlakatlarda gapiriladi.", "English is spoken in many countries.", ["speaked"]),
    s("Non har kuni pishiriladi.", "Bread is baked every day.", ["bake"]),
    s("Paxta O'zbekistonda yetishtiriladi.", "Cotton is grown in Uzbekistan.", ["growed"]),
    s("Bu do'konda telefonlar sotiladi.", "Phones are sold in this shop.", ["is"], [
      "Phones are sold in this store.",
      "Mobile phones are sold in this shop.",
      "Mobile phones are sold in this store.",
    ]),
    s("Bu mashinalar Koreyada ishlab chiqariladi.", "These cars are made in Korea.", ["is"], [
      "These cars are produced in Korea.",
      "These cars are manufactured in Korea.",
    ]),
    s("Xona har kuni tozalanadi.", "The room is cleaned every day.", ["clean"]),
    s("Bu uy 1990-yilda qurilgan.", "This house was built in 1990.", ["builded"]),
    s("Bu ko'prik o'tgan yili qurilgan.", "This bridge was built last year.", ["is"]),
    s("Mening velosipedim kecha o'g'irlandi.", "My bike was stolen yesterday.", ["stealed"], ["My bicycle was stolen yesterday."]),
    s("Telefon 1876-yilda ixtiro qilingan.", "The telephone was invented in 1876.", ["invent"], ["The phone was invented in 1876."]),
    s("Bu xatlar ingliz tilida yozilgan.", "These letters were written in English.", ["was"]),
    s("Biz to'yga taklif qilindik.", "We were invited to the wedding.", ["was"]),
    s("Bu rasm Malika tomonidan chizilgan.", "This picture was drawn by Malika.", ["from", "drew"], ["This picture was painted by Malika."]),
    s("Bu kitob Aziz tomonidan yozilgan.", "This book was written by Aziz.", ["wrote"]),
    s("Choy Ali tomonidan tayyorlandi.", "The tea was made by Ali.", ["make"]),
    s("Darslar Sardor tomonidan o'tiladi.", "The lessons are taught by Sardor.", ["teached"]),
    s("Bu xona kecha tozalanmadi.", "This room wasn't cleaned yesterday.", ["isn't"]),
    s("Ingliz tili bu maktabda o'qitilmaydi.", "English isn't taught at this school.", ["teached"], ["English isn't taught in this school."]),
    s("Xatlar yuborilmadi.", "The letters weren't sent.", ["wasn't"]),
    s("Bolalar ziyofatga taklif qilinmadi.", "The children weren't invited to the party.", ["wasn't"]),
    s("Bu telefon qayerda ishlab chiqarilgan?", "Where was this phone made?", ["did"], [
      "Where was this phone produced?",
      "Where was this phone manufactured?",
    ]),
    s("Bu uy qachon qurilgan?", "When was this house built?", ["did"]),
    s("Bu kitob kim tomonidan yozilgan?", "Who was this book written by?", ["wrote"], ["By whom was this book written?"]),
    s("Bu mashinalar Germaniyada ishlab chiqariladimi?", "Are these cars made in Germany?", ["do"], [
      "Are these cars produced in Germany?",
      "Are these cars manufactured in Germany?",
    ]),
    s("Bu do'konda kitoblar sotiladimi?", "Are books sold in this shop?", ["do"], ["Are books sold in this store?"]),
    s("Sen tug'ilgan kun ziyofatiga taklif qilindingmi?", "Were you invited to the birthday party?", ["did"]),
    s("Men 2010-yilda tug'ilganman.", "I was born in 2010.", ["am"]),
    s("Registon XV asrda qurilgan.", "The Registan was built in the 15th century.", ["is"], [
      "The Registan was built in the fifteenth century.",
      "Registan was built in the 15th century.",
      "Registan was built in the fifteenth century.",
    ]),
    s("Palov guruch, go'sht va sabzidan tayyorlanadi.", "Plov is made with rice, meat and carrots.", ["make"], [
      "Plov is made from rice, meat and carrots.",
      "Plov is made of rice, meat and carrots.",
      "Plov is cooked with rice, meat and carrots.",
    ]),
    s("Bu mashinalar Toshkentda ishlab chiqariladi va Rossiyaga sotiladi.", "These cars are made in Tashkent and sold to Russia.", ["is"], [
      "These cars are made in Tashkent and are sold to Russia.",
      "These cars are produced in Tashkent and sold to Russia.",
      "These cars are produced in Tashkent and are sold to Russia.",
      "These cars are manufactured in Tashkent and sold to Russia.",
      "These cars are manufactured in Tashkent and are sold to Russia.",
    ]),
  ],
  test: [
    s("Rus tili bu mamlakatda gapiriladi.", "Russian is spoken in this country.", ["speaked"]),
    s("Bu do'konda mevalar sotiladi.", "Fruit is sold in this shop.", ["sell"], [
      "Fruit is sold in this store.",
      "Fruits are sold in this shop.",
      "Fruits are sold in this store.",
    ]),
    s("Bu telefonlar Xitoyda ishlab chiqariladi.", "These phones are made in China.", ["is"], [
      "These phones are produced in China.",
      "These phones are manufactured in China.",
    ]),
    s("Ofis har kuni ertalab tozalanadi.", "The office is cleaned every morning.", ["clean"]),
    s("Uzum Samarqandda yetishtiriladi.", "Grapes are grown in Samarkand.", ["is"]),
    s("Bu maktab 1985-yilda qurilgan.", "This school was built in 1985.", ["builded"]),
    s("Mening telefonim avtobusda o'g'irlandi.", "My phone was stolen on the bus.", ["stealed"], ["My mobile phone was stolen on the bus."]),
    s("Kompyuter qachon ixtiro qilingan?", "When was the computer invented?", ["did"]),
    s("Bu rasmlar Kamola tomonidan chizilgan.", "These pictures were drawn by Kamola.", ["was"], ["These pictures were painted by Kamola."]),
    s("Bu qo'shiq Timur tomonidan yozilgan.", "This song was written by Timur.", ["wrote"]),
    s("Biz Zarinaning to'yiga taklif qilindik.", "We were invited to Zarina's wedding.", ["was"]),
    s("Ovqat onam tomonidan pishirildi.", "The food was cooked by my mother.", ["cook"], [
      "The food was cooked by my mum.",
      "The food was cooked by my mom.",
      "The meal was cooked by my mother.",
      "The meal was cooked by my mum.",
      "The meal was cooked by my mom.",
      "Dinner was cooked by my mother.",
      "Dinner was cooked by my mum.",
      "Dinner was cooked by my mom.",
    ]),
    s("Xat kecha yuborilmadi.", "The letter wasn't sent yesterday.", ["weren't"]),
    s("Bu do'konda gazetalar sotilmaydi.", "Newspapers aren't sold in this shop.", ["isn't"], ["Newspapers aren't sold in this store."]),
    s("Kalitlar topilmadi.", "The keys weren't found.", ["wasn't"]),
    s("Sening soating qayerda ishlab chiqarilgan?", "Where was your watch made?", ["did"], [
      "Where was your watch produced?",
      "Where was your watch manufactured?",
    ]),
    s("Sizning maktabingizda ingliz tili o'qitiladimi?", "Is English taught at your school?", ["teached"], ["Is English taught in your school?"]),
    s("Ular to'yga taklif qilindimi?", "Were they invited to the wedding?", ["did"]),
    s("Sardor 2005-yilda Buxoroda tug'ilgan.", "Sardor was born in Bukhara in 2005.", ["is"], ["Sardor was born in 2005 in Bukhara."]),
    s("Bu masjid 500 yil oldin qurilgan.", "This mosque was built 500 years ago.", ["is"], ["This mosque was built five hundred years ago."]),
  ],
};

/* ───────────────────────────── 17. Relative clauses ───────────────────────────── */

const RELATIVE_CLAUSES: GrammarTopicContent = {
  slug: "a2-relative-clauses",
  level: "A2",
  position: 17,
  title: { en: "Relative clauses: who, which, that, where", uz: "Aniqlovchi ergash gaplar: who, which, that, where" },
  explanation: {
    uz: [
      "Relative clause kimni yoki nimani nazarda tutayotganimizni aniqlaydi: the man who lives next door = qo'shnida yashaydigan odam.",
      "Diqqat: o'zbek tilida aniqlovchi otdan OLDIN keladi (men sotib olgan kitob), ingliz tilida esa KEYIN: the book which I bought.",
      "who - odamlar uchun: The girl who sings is my sister.",
      "which - narsa va hayvonlar uchun: The bus which goes to Tashkent is here.",
      "that - odam va narsalar uchun who / which o'rniga ishlatilsa bo'ladi: the man that lives here, the book that I bought.",
      "where - joylar uchun: the town where I was born = men tug'ilgan shahar.",
      "who / which dan keyin he, she, it qo'shilmaydi: the man who lives here (the man who he lives here emas).",
    ].join("\n"),
    pattern: "person + who / that … · thing + which / that … · place + where + subject + verb",
    examples: [
      { en: "This is the man who lives next door.", uz: "Bu qo'shnida yashaydigan odam." },
      { en: "The book which I bought is very interesting.", uz: "Men sotib olgan kitob juda qiziq." },
      { en: "This is the town where I was born.", uz: "Bu men tug'ilgan shahar." },
      { en: "I know a girl that speaks French.", uz: "Men frantsuz tilida gapiradigan bir qizni bilaman." },
    ],
  },
  build: [
    s("Bu qo'shnida yashaydigan odam.", "This is the man who lives next door.", ["which"], ["This is the man that lives next door."]),
    s("Men ingliz tilidan dars beradigan ayolni bilaman.", "I know the woman who teaches English.", ["which"], ["I know the woman that teaches English."]),
    s("Bizda ingliz tilida gapiradigan o'qituvchi bor.", "We have a teacher who speaks English.", ["which"], [
      "We have a teacher that speaks English.",
      "We have got a teacher who speaks English.",
      "We have got a teacher that speaks English.",
    ]),
    s("Ali - Toshkentda ishlaydigan shifokor.", "Ali is a doctor who works in Tashkent.", ["which"], ["Ali is a doctor that works in Tashkent."]),
    s("Menda ko'p gapiradigan to'tiqush bor.", "I have a parrot which talks a lot.", ["where"], [
      "I have a parrot that talks a lot.",
      "I have got a parrot which talks a lot.",
      "I have got a parrot that talks a lot.",
    ]),
    s("Bu Londonga boradigan avtobus.", "This is the bus which goes to London.", ["who"], ["This is the bus that goes to London."]),
    s("Men stol ustidagi kitobni xohlayman.", "I want the book which is on the table.", ["who"], ["I want the book that is on the table."]),
    s("Sen menga bergan kitob juda qiziq.", "The book which you gave me is very interesting.", ["who"], [
      "The book that you gave me is very interesting.",
      "The book you gave me is very interesting.",
    ]),
    s("Men kecha sotib olgan telefon yangi.", "The phone which I bought yesterday is new.", ["who"], [
      "The phone that I bought yesterday is new.",
      "The phone I bought yesterday is new.",
    ]),
    s("Biz ko'rgan film zerikarli edi.", "The film which we watched was boring.", ["who"], [
      "The film that we watched was boring.",
      "The film we watched was boring.",
      "The movie which we watched was boring.",
      "The movie that we watched was boring.",
      "The movie we watched was boring.",
      "The film which we saw was boring.",
      "The film that we saw was boring.",
      "The film we saw was boring.",
      "The movie which we saw was boring.",
      "The movie that we saw was boring.",
      "The movie we saw was boring.",
    ]),
    s("Bu men tug'ilgan shahar.", "This is the town where I was born.", ["which"], [
      "This is the city where I was born.",
      "This is the town I was born in.",
      "This is the city I was born in.",
    ]),
    s("Bu biz yashaydigan uy.", "This is the house where we live.", ["which"], [
      "This is the house we live in.",
      "This is the house that we live in.",
      "This is the house which we live in.",
    ]),
    s("Men ishlaydigan ofis shahar markazida.", "The office where I work is in the city centre.", ["which"], [
      "The office where I work is in the city center.",
      "The office I work in is in the city centre.",
      "The office I work in is in the city center.",
      "The office where I work is in the town centre.",
      "The office where I work is in the centre.",
      "The office where I work is in the center.",
    ]),
    s("Biz ovqatlanadigan restoran juda yaxshi.", "The restaurant where we eat is very good.", ["which"], [
      "The restaurant we eat at is very good.",
      "The restaurant that we eat at is very good.",
      "The restaurant which we eat at is very good.",
      "The restaurant where we eat is very nice.",
    ]),
    s("Men o'qiydigan maktab katta.", "The school where I study is big.", ["which"], [
      "The school where I study is large.",
      "The school I study at is big.",
      "The school that I study at is big.",
      "The school I go to is big.",
      "The school that I go to is big.",
    ]),
    s("Malika - Buxoroda yashaydigan qiz.", "Malika is the girl who lives in Bukhara.", ["which"], [
      "Malika is the girl that lives in Bukhara.",
      "Malika is a girl who lives in Bukhara.",
      "Malika is a girl that lives in Bukhara.",
    ]),
    s("Sen gaplashgan odam mening otam.", "The man who you talked to is my father.", ["which"], [
      "The man that you talked to is my father.",
      "The man you talked to is my father.",
      "The man who you spoke to is my father.",
      "The man that you spoke to is my father.",
      "The man you spoke to is my father.",
      "The man who you talked to is my dad.",
      "The man that you talked to is my dad.",
      "The man you talked to is my dad.",
    ]),
    s("Ular sotgan mashina eski edi.", "The car which they sold was old.", ["who"], [
      "The car that they sold was old.",
      "The car they sold was old.",
    ]),
    s("U (yigit) meni tushunadigan yagona do'st.", "He is the only friend who understands me.", ["which"], ["He is the only friend that understands me."]),
    s("Uchrashuvga kelmagan talabalar uyda qolishdi.", "The students who didn't come to the meeting stayed at home.", ["which"], [
      "The students that didn't come to the meeting stayed at home.",
      "The students who didn't come to the meeting stayed home.",
      "The students that didn't come to the meeting stayed home.",
    ]),
    s("Kamola bilan gaplashayotgan yigit mening akam.", "The boy who is talking to Kamola is my brother.", ["which"], [
      "The boy that is talking to Kamola is my brother.",
      "The boy talking to Kamola is my brother.",
      "The boy who is talking to Kamola is my older brother.",
      "The boy that is talking to Kamola is my older brother.",
      "The boy who is speaking to Kamola is my brother.",
    ]),
    s("Men senga aytgan kafe shu yerda.", "The cafe which I told you about is here.", ["where"], [
      "The cafe that I told you about is here.",
      "The cafe I told you about is here.",
    ]),
    s("Sevara ishlaydigan kasalxona yangi.", "The hospital where Sevara works is new.", ["which"], [
      "The hospital Sevara works in is new.",
      "The hospital that Sevara works in is new.",
      "The hospital which Sevara works in is new.",
      "The hospital Sevara works at is new.",
      "The hospital that Sevara works at is new.",
    ]),
    s("Biz uchrashgan joyni eslaysanmi?", "Do you remember the place where we met?", ["which"], [
      "Do you remember the place we met?",
      "Do you remember the place where we first met?",
    ]),
    s("Menga Toshkentga boradigan poyezd kerak.", "I need the train which goes to Tashkent.", ["who"], [
      "I need the train that goes to Tashkent.",
      "I need a train which goes to Tashkent.",
      "I need a train that goes to Tashkent.",
    ]),
    s("Bu Jasur menga bergan sovg'a.", "This is the present which Jasur gave me.", ["who"], [
      "This is the present that Jasur gave me.",
      "This is the present Jasur gave me.",
      "This is the gift which Jasur gave me.",
      "This is the gift that Jasur gave me.",
      "This is the gift Jasur gave me.",
    ]),
    s("Bu yerda ishlaydigan odamlar juda mehribon.", "The people who work here are very kind.", ["which"], [
      "The people that work here are very kind.",
      "The people who work here are very friendly.",
      "The people that work here are very friendly.",
    ]),
    s("Samarqand - men o'tgan yili borgan shahar.", "Samarkand is the city which I visited last year.", ["where"], [
      "Samarkand is the city that I visited last year.",
      "Samarkand is the city I visited last year.",
      "Samarkand is the city where I went last year.",
      "Samarkand is the city I went to last year.",
      "Samarkand is the city that I went to last year.",
    ]),
    s("Biz qolgan mehmonxona dengiz yonida edi.", "The hotel where we stayed was near the sea.", ["which"], [
      "The hotel we stayed at was near the sea.",
      "The hotel that we stayed at was near the sea.",
      "The hotel which we stayed at was near the sea.",
      "The hotel where we stayed was next to the sea.",
      "The hotel where we stayed was by the sea.",
    ]),
    s("Men Londonda tanishgan qiz hozir Toshkentda yashaydi.", "The girl who I met in London now lives in Tashkent.", ["which"], [
      "The girl that I met in London now lives in Tashkent.",
      "The girl I met in London now lives in Tashkent.",
      "The girl who I met in London lives in Tashkent now.",
      "The girl that I met in London lives in Tashkent now.",
      "The girl I met in London lives in Tashkent now.",
    ]),
  ],
  test: [
    s("Men frantsuz tilida gapiradigan qizni bilaman.", "I know a girl who speaks French.", ["which"], [
      "I know a girl that speaks French.",
      "I know the girl who speaks French.",
      "I know the girl that speaks French.",
    ]),
    s("Dilnoza - kasalxonada ishlaydigan hamshira.", "Dilnoza is a nurse who works in a hospital.", ["which"], [
      "Dilnoza is a nurse that works in a hospital.",
      "Dilnoza is a nurse who works at a hospital.",
      "Dilnoza is a nurse that works at a hospital.",
      "Dilnoza is a nurse who works in the hospital.",
      "Dilnoza is a nurse that works in the hospital.",
    ]),
    s("Bu Samarqandga boradigan poyezd.", "This is the train which goes to Samarkand.", ["who"], ["This is the train that goes to Samarkand."]),
    s("Men kecha o'qigan kitob juda qiziq edi.", "The book which I read yesterday was very interesting.", ["who"], [
      "The book that I read yesterday was very interesting.",
      "The book I read yesterday was very interesting.",
    ]),
    s("Bu men ishlaydigan bank.", "This is the bank where I work.", ["which"], [
      "This is the bank I work at.",
      "This is the bank I work in.",
      "This is the bank that I work at.",
      "This is the bank which I work at.",
      "This is the bank that I work in.",
      "This is the bank which I work in.",
    ]),
    s("Bu ota-onam yashaydigan qishloq.", "This is the village where my parents live.", ["which"], [
      "This is the village my parents live in.",
      "This is the village that my parents live in.",
      "This is the village which my parents live in.",
    ]),
    s("Sen menga yuborgan xatni oldim.", "I got the letter which you sent me.", ["who"], [
      "I got the letter that you sent me.",
      "I got the letter you sent me.",
      "I received the letter which you sent me.",
      "I received the letter that you sent me.",
      "I received the letter you sent me.",
    ]),
    s("Biz yashaydigan ko'cha juda tinch.", "The street where we live is very quiet.", ["which"], [
      "The street we live on is very quiet.",
      "The street that we live on is very quiet.",
      "The street which we live on is very quiet.",
      "The street we live in is very quiet.",
    ]),
    s("Bizga yordam bergan odam politsiyachi edi.", "The man who helped us was a police officer.", ["which"], [
      "The man that helped us was a police officer.",
      "The man who helped us was a policeman.",
      "The man that helped us was a policeman.",
      "The person who helped us was a police officer.",
      "The person that helped us was a police officer.",
    ]),
    s("Bekzod sotgan velosiped yangi edi.", "The bike which Bekzod sold was new.", ["who"], [
      "The bike that Bekzod sold was new.",
      "The bike Bekzod sold was new.",
      "The bicycle which Bekzod sold was new.",
      "The bicycle that Bekzod sold was new.",
      "The bicycle Bekzod sold was new.",
    ]),
    s("Futbol o'ynashni yaxshi ko'radigan bolalar bog'da.", "The children who like playing football are in the park.", ["which"], [
      "The children that like playing football are in the park.",
      "The children who like to play football are in the park.",
      "The children that like to play football are in the park.",
      "The children who love playing football are in the park.",
      "The children that love playing football are in the park.",
      "The children who love to play football are in the park.",
      "The children that love to play football are in the park.",
    ]),
    s("Bu otam ishlaydigan zavod.", "This is the factory where my father works.", ["which"], [
      "This is the factory where my dad works.",
      "This is the factory my father works in.",
      "This is the factory my father works at.",
      "This is the factory that my father works in.",
      "This is the factory my dad works in.",
      "This is the factory my dad works at.",
    ]),
    s("Bu sen qidirayotgan kitobmi?", "Is this the book which you are looking for?", ["who"], [
      "Is this the book that you are looking for?",
      "Is this the book you are looking for?",
    ]),
    s("Bizga ingliz tilini o'rgatadigan o'qituvchi Londondan.", "The teacher who teaches us English is from London.", ["which"], [
      "The teacher that teaches us English is from London.",
    ]),
    s("Men kecha tanishgan odam shifokor.", "The man who I met yesterday is a doctor.", ["which"], [
      "The man that I met yesterday is a doctor.",
      "The man I met yesterday is a doctor.",
      "The man whom I met yesterday is a doctor.",
    ]),
    s("Bu biz birinchi marta uchrashgan kafe.", "This is the cafe where we first met.", ["which"], [
      "This is the cafe where we met for the first time.",
      "This is the cafe we first met in.",
      "This is the cafe that we first met in.",
      "This is the cafe which we first met in.",
      "This is the cafe we first met at.",
    ]),
    s("Madina pishirgan tort juda mazali edi.", "The cake which Madina made was very tasty.", ["who"], [
      "The cake that Madina made was very tasty.",
      "The cake Madina made was very tasty.",
      "The cake which Madina baked was very tasty.",
      "The cake that Madina baked was very tasty.",
      "The cake Madina baked was very tasty.",
      "The cake which Madina made was very delicious.",
      "The cake that Madina made was very delicious.",
      "The cake Madina made was very delicious.",
      "The cake which Madina baked was very delicious.",
      "The cake that Madina baked was very delicious.",
      "The cake Madina baked was very delicious.",
    ]),
    s("Biz ko'rgan uy juda katta edi.", "The house which we saw was very big.", ["who"], [
      "The house that we saw was very big.",
      "The house we saw was very big.",
      "The house which we saw was very large.",
      "The house that we saw was very large.",
      "The house we saw was very large.",
    ]),
    s("Mening Toshkentda yashaydigan do'stlarim bor.", "I have friends who live in Tashkent.", ["which"], [
      "I have friends that live in Tashkent.",
      "I have got friends who live in Tashkent.",
      "I have got friends that live in Tashkent.",
      "I have some friends who live in Tashkent.",
      "I have some friends that live in Tashkent.",
    ]),
    s("Men ingliz tilini o'rganadigan markaz uyimga yaqin.", "The centre where I learn English is near my house.", ["which"], [
      "The center where I learn English is near my house.",
      "The centre where I learn English is near my home.",
      "The center where I learn English is near my home.",
      "The centre where I study English is near my house.",
      "The center where I study English is near my house.",
    ]),
  ],
};

/* ───────────────────────── 18. Subject / object questions ───────────────────────── */

const SUBJECT_OBJECT_QUESTIONS: GrammarTopicContent = {
  slug: "a2-subject-object-questions",
  level: "A2",
  position: 18,
  title: { en: "Subject and object questions", uz: "Ega va to'ldiruvchiga beriladigan so'roqlar" },
  explanation: {
    uz: [
      "Ega haqida so'raganda (kim / nima qildi?) do / does / did ishlatilmaydi: Who called you? = Senga kim qo'ng'iroq qildi?",
      "Bunda fe'l darak gapdagidek: hozirgi zamonda -s oladi, o'tgan zamonda V2: Who lives here? Who broke the window?",
      "To'ldiruvchi haqida so'raganda (kimni / kimga / nimani?) oddiy so'roq tartibi: do / does / did + ega + fe'l: Who did you call? = Sen kimga qo'ng'iroq qilding?",
      "Taqqoslang: Who loves Ali? (Alini kim yaxshi ko'radi?) - Who does Ali love? (Ali kimni yaxshi ko'radi?)",
      "What happened? = Nima bo'ldi? (What did happen emas).",
      "Which / How many + ot ham ega bo'lishi mumkin: Which bus goes to Tashkent? How many people came?",
    ].join("\n"),
    pattern: "subject question: Who / What / Which + noun + verb (V-s / V2)? · object question: Who / What + do / does / did + subject + verb?",
    examples: [
      { en: "Who called you?", uz: "Senga kim qo'ng'iroq qildi?" },
      { en: "Who did you call?", uz: "Sen kimga qo'ng'iroq qilding?" },
      { en: "What happened yesterday?", uz: "Kecha nima bo'ldi?" },
      { en: "Which bus goes to Tashkent?", uz: "Toshkentga qaysi avtobus boradi?" },
    ],
  },
  build: [
    s("Senga kim qo'ng'iroq qildi?", "Who called you?", ["did"], ["Who phoned you?", "Who rang you?"]),
    s("Sen kimga qo'ng'iroq qilding?", "Who did you call?", ["called"], ["Who did you phone?", "Who did you ring?"]),
    s("Kecha nima bo'ldi?", "What happened yesterday?", ["did"]),
    s("Bu yerda kim yashaydi?", "Who lives here?", ["does"]),
    s("Sen bu yerda kimni bilasan?", "Who do you know here?", ["knows"]),
    s("Derazani kim sindirdi?", "Who broke the window?", ["did"]),
    s("Sen nimani sindirding?", "What did you break?", ["broke"]),
    s("Kim ingliz tilida gapiradi?", "Who speaks English?", ["does"], ["Who can speak English?"]),
    s("Sen kim bilan gaplashding?", "Who did you talk to?", ["talked"], [
      "Who did you speak to?",
      "Who did you talk with?",
      "Who did you speak with?",
      "Who were you talking to?",
    ]),
    s("Toshkentga qaysi avtobus boradi?", "Which bus goes to Tashkent?", ["does"]),
    s("Sen qaysi avtobusda yurasan?", "Which bus do you take?", ["takes"]),
    s("Alini kim yaxshi ko'radi?", "Who loves Ali?", ["does"], ["Who likes Ali?"]),
    s("Ali kimni yaxshi ko'radi?", "Who does Ali love?", ["loves"], ["Who does Ali like?"]),
    s("Sen kecha kimni ko'rding?", "Who did you see yesterday?", ["saw"]),
    s("Kecha seni kim ko'rdi?", "Who saw you yesterday?", ["did"]),
    s("Bu kitobni kim yozgan?", "Who wrote this book?", ["did"]),
    s("Sen nima yozding?", "What did you write?", ["wrote"]),
    s("Ziyofatga necha kishi keldi?", "How many people came to the party?", ["did"]),
    s("Sen nechta kitob sotib olding?", "How many books did you buy?", ["bought"]),
    s("Sening telefoningga nima bo'ldi?", "What happened to your phone?", ["did"]),
    s("Sardorga kim yordam berdi?", "Who helped Sardor?", ["did"]),
    s("Sardor kimga yordam berdi?", "Who did Sardor help?", ["helped"]),
    s("Kamolaga kim xat yozdi?", "Who wrote a letter to Kamola?", ["did"], ["Who wrote Kamola a letter?"]),
    s("Seni nima qo'rqitdi?", "What scared you?", ["did"], ["What frightened you?"]),
    s("Bu yerda kim ishlaydi?", "Who works here?", ["does"]),
    s("Dilnoza nimani yoqtiradi?", "What does Dilnoza like?", ["likes"]),
    s("O'yinda qaysi jamoa yutdi?", "Which team won the game?", ["did"], ["Which team won the match?"]),
    s("Sen qaysi jamoaga muxlislik qilasan?", "Which team do you support?", ["supports"]),
    s("Bugun ertalab eshikni kim taqillatdi?", "Who knocked on the door this morning?", ["did"], ["Who knocked at the door this morning?"]),
    s("O'tgan hafta maktabingizda nima bo'ldi?", "What happened at your school last week?", ["did"], ["What happened in your school last week?"]),
  ],
  test: [
    s("Senga kim xat yozdi?", "Who wrote you a letter?", ["did"], ["Who wrote a letter to you?", "Who wrote to you?"]),
    s("Sen kimga xat yozding?", "Who did you write to?", ["wrote"], ["Who did you write a letter to?"]),
    s("Bu yerda nima bo'ldi?", "What happened here?", ["did"]),
    s("Bu uyda kim yashaydi?", "Who lives in this house?", ["does"]),
    s("Sen Toshkentda kimni bilasan?", "Who do you know in Tashkent?", ["knows"]),
    s("Mening choyimni kim ichdi?", "Who drank my tea?", ["did"]),
    s("Sen nima ichding?", "What did you drink?", ["drank"]),
    s("Samarqandga qaysi poyezd boradi?", "Which train goes to Samarkand?", ["does"]),
    s("Sen qaysi kitobni o'qiding?", "Which book did you read?", ["readed"]),
    s("Malikani kim taklif qildi?", "Who invited Malika?", ["did"]),
    s("Malika kimni taklif qildi?", "Who did Malika invite?", ["invited"]),
    s("Darsga nechta talaba keldi?", "How many students came to the lesson?", ["did"], [
      "How many students came to class?",
      "How many students came to the class?",
    ]),
    s("Sen nechta olma yeding?", "How many apples did you eat?", ["ate"]),
    s("Akangga nima bo'ldi?", "What happened to your brother?", ["did"], ["What happened to your older brother?"]),
    s("Kim pianino chaladi?", "Who plays the piano?", ["does"], ["Who plays piano?", "Who can play the piano?"]),
    s("Sen kecha kechqurun nima qilding?", "What did you do yesterday evening?", ["done"], ["What did you do last night?"]),
    s("Bu rasmni kim chizdi?", "Who drew this picture?", ["did"], ["Who painted this picture?"]),
    s("Sizga qaysi o'qituvchi ingliz tilidan dars beradi?", "Which teacher teaches you English?", ["does"]),
    s("Sening kalitlaringni kim topdi?", "Who found your keys?", ["did"]),
    s("Sen ziyofatda kim bilan raqsga tushding?", "Who did you dance with at the party?", ["danced"]),
  ],
};

/* ───────────────────────────── 19. So / Neither ───────────────────────────── */

const SO_NEITHER: GrammarTopicContent = {
  slug: "a2-so-neither",
  level: "A2",
  position: 19,
  title: { en: "So do I / Neither do I", uz: "So do I / Neither do I (... ham)" },
  explanation: {
    uz: [
      "\"Men ham\", \"U ham\" deb qisqa javob berish uchun: So / Neither + yordamchi fe'l + ega.",
      "Tasdiq gapga So: I like tea. - So do I. = Men choyni yaxshi ko'raman. - Men ham.",
      "Inkor gapga Neither (yoki Nor): I can't swim. - Neither can I. = Men suza olmayman. - Men ham.",
      "Yordamchi fe'l birinchi gapdagidek: am / is / are, was / were, can, have / has, will. Fe'l bo'lmasa: do / does (hozirgi), did (o'tgan): She went home. - So did I.",
      "Neither'dan keyin fe'l tasdiq shaklda: Neither do I (Neither don't I emas).",
      "Tartib: So / Neither + fe'l + ega: So do I (So I do emas), So is Ali.",
      "Og'zaki nutqda Me too / Me neither ham bor, lekin bu mavzuda to'liq shaklni yozing.",
    ].join("\n"),
    pattern: "positive → So + auxiliary + subject (So do I. So was she.) · negative → Neither / Nor + auxiliary + subject (Neither can I.)",
    examples: [
      { en: "I like tea. So do I.", uz: "Men choyni yaxshi ko'raman. - Men ham." },
      { en: "I can't swim. Neither can I.", uz: "Men suza olmayman. - Men ham." },
      { en: "Ali is tired. So is Madina.", uz: "Ali charchagan. - Madina ham." },
      { en: "Kamola didn't come. Neither did Zarina.", uz: "Kamola kelmadi. - Zarina ham." },
    ],
  },
  build: [
    s("Men choyni yaxshi ko'raman. - Men ham.", "I like tea. So do I.", ["neither"], ["I love tea. So do I."]),
    s("Men charchadim. - Men ham.", "I am tired. So am I.", ["do"]),
    s("Men suza olmayman. - Men ham.", "I can't swim. Neither can I.", ["so"], ["I can't swim. Nor can I."]),
    s("Men qahvani yoqtirmayman. - Men ham.", "I don't like coffee. Neither do I.", ["so"], ["I don't like coffee. Nor do I."]),
    s("Men talabaman. - Men ham.", "I am a student. So am I.", ["do"]),
    s("Men ingliz tilida gapira olaman. - Men ham.", "I can speak English. So can I.", ["do"]),
    s("Men och emasman. - Men ham.", "I'm not hungry. Neither am I.", ["do"], ["I'm not hungry. Nor am I."]),
    s("Men kecha kinoga bordim. - Men ham.", "I went to the cinema yesterday. So did I.", ["do"], [
      "I went to the movies yesterday. So did I.",
    ]),
    s("Men filmni ko'rmadim. - Men ham.", "I didn't see the film. Neither did I.", ["so"], [
      "I didn't see the film. Nor did I.",
      "I didn't see the movie. Neither did I.",
      "I didn't see the movie. Nor did I.",
      "I didn't watch the film. Neither did I.",
      "I didn't watch the film. Nor did I.",
      "I didn't watch the movie. Neither did I.",
      "I didn't watch the movie. Nor did I.",
    ]),
    s("Men kecha uyda edim. - Men ham.", "I was at home yesterday. So was I.", ["did"], ["I was home yesterday. So was I."]),
    s("Men u yerda emas edim. - Men ham.", "I wasn't there. Neither was I.", ["did"], ["I wasn't there. Nor was I."]),
    s("Ali charchagan. - Madina ham.", "Ali is tired. So is Madina.", ["does"]),
    s("Jasur futbol o'ynaydi. - Sardor ham.", "Jasur plays football. So does Sardor.", ["do"]),
    s("Kamola go'sht yemaydi. - Zarina ham.", "Kamola doesn't eat meat. Neither does Zarina.", ["do"], ["Kamola doesn't eat meat. Nor does Zarina."]),
    s("Aziz mashina hayday olmaydi. - Bekzod ham.", "Aziz can't drive. Neither can Bekzod.", ["does"], [
      "Aziz can't drive. Nor can Bekzod.",
      "Aziz can't drive a car. Neither can Bekzod.",
      "Aziz can't drive a car. Nor can Bekzod.",
    ]),
    s("Men Toshkentda yashayman. - Men ham.", "I live in Tashkent. So do I.", ["am"]),
    s("Men Samarqandda tug'ilganman. - Men ham.", "I was born in Samarkand. So was I.", ["did"]),
    s("Ular tayyor emas. - Biz ham.", "They aren't ready. Neither are we.", ["do"], ["They aren't ready. Nor are we."]),
    s("Men Buxoroda bo'lganman. - Men ham.", "I have been to Bukhara. So have I.", ["did"]),
    s("Men hali tushlik qilmadim. - Men ham.", "I haven't had lunch yet. Neither have I.", ["did"], [
      "I haven't had lunch yet. Nor have I.",
      "I haven't eaten lunch yet. Neither have I.",
      "I haven't eaten lunch yet. Nor have I.",
    ]),
    s("Men ertaga kelaman. - Men ham.", "I will come tomorrow. So will I.", ["do"]),
    s("Men bu oqshom hech qayerga chiqmayman. - Men ham.", "I won't go out tonight. Neither will I.", ["do"], ["I won't go out tonight. Nor will I."]),
    s("Sevara musiqani yaxshi ko'radi. - Uning singlisi ham.", "Sevara loves music. So does her sister.", ["do"], [
      "Sevara likes music. So does her sister.",
      "Sevara loves music. So does her younger sister.",
      "Sevara likes music. So does her younger sister.",
    ]),
    s("Otam choy ichmaydi. - Onam ham.", "My father doesn't drink tea. Neither does my mother.", ["do"], [
      "My father doesn't drink tea. Nor does my mother.",
      "My dad doesn't drink tea. Neither does my mum.",
      "My dad doesn't drink tea. Nor does my mum.",
      "My dad doesn't drink tea. Neither does my mom.",
      "My dad doesn't drink tea. Nor does my mom.",
    ]),
    s("Ular kecha juda band edi. - Biz ham.", "They were very busy yesterday. So were we.", ["was"]),
    s("Men uyga piyoda keldim. - Malika ham.", "I walked home. So did Malika.", ["does"]),
    s("Men buni tushunmadim. - Men ham.", "I didn't understand this. Neither did I.", ["so"], [
      "I didn't understand this. Nor did I.",
      "I didn't understand it. Neither did I.",
      "I didn't understand it. Nor did I.",
    ]),
    s("Ali ingliz tilini o'rganyapti. - Nilufar ham.", "Ali is learning English. So is Nilufar.", ["does"]),
    s("Men yomg'irli kunlarni yoqtirmayman. - Men ham.", "I don't like rainy days. Neither do I.", ["so"], ["I don't like rainy days. Nor do I."]),
    s("Men o'tgan yozda Londonga bordim. - Akam ham.", "I went to London last summer. So did my brother.", ["was"], [
      "I went to London last summer. So did my older brother.",
    ]),
  ],
  test: [
    s("Men olmani yaxshi ko'raman. - Men ham.", "I like apples. So do I.", ["neither"], ["I love apples. So do I."]),
    s("Men kasalman. - Men ham.", "I am ill. So am I.", ["do"], ["I am sick. So am I."]),
    s("Men gitara chala olmayman. - Men ham.", "I can't play the guitar. Neither can I.", ["so"], [
      "I can't play the guitar. Nor can I.",
      "I can't play guitar. Neither can I.",
      "I can't play guitar. Nor can I.",
    ]),
    s("Men sutni yoqtirmayman. - Men ham.", "I don't like milk. Neither do I.", ["so"], ["I don't like milk. Nor do I."]),
    s("Men o'qituvchiman. - Men ham.", "I am a teacher. So am I.", ["do"]),
    s("Men rus tilida gapira olaman. - Men ham.", "I can speak Russian. So can I.", ["do"]),
    s("Men charchaganim yo'q. - Men ham.", "I'm not tired. Neither am I.", ["do"], ["I'm not tired. Nor am I."]),
    s("Men kecha bozorga bordim. - Men ham.", "I went to the market yesterday. So did I.", ["do"], [
      "I went to the bazaar yesterday. So did I.",
    ]),
    s("Men kecha televizor ko'rmadim. - Men ham.", "I didn't watch TV yesterday. Neither did I.", ["so"], [
      "I didn't watch TV yesterday. Nor did I.",
      "I didn't watch television yesterday. Neither did I.",
      "I didn't watch television yesterday. Nor did I.",
    ]),
    s("Men kecha kasal edim. - Men ham.", "I was ill yesterday. So was I.", ["did"], ["I was sick yesterday. So was I."]),
    s("Dilnoza uyda. - Timur ham.", "Dilnoza is at home. So is Timur.", ["does"], ["Dilnoza is home. So is Timur."]),
    s("Bekzod tennis o'ynaydi. - Aziz ham.", "Bekzod plays tennis. So does Aziz.", ["do"]),
    s("Malika qahva ichmaydi. - Sevara ham.", "Malika doesn't drink coffee. Neither does Sevara.", ["do"], ["Malika doesn't drink coffee. Nor does Sevara."]),
    s("Men Samarqandda bo'lmaganman. - Men ham.", "I haven't been to Samarkand. Neither have I.", ["did"], ["I haven't been to Samarkand. Nor have I."]),
    s("Men uy vazifamni qilib bo'ldim. - Men ham.", "I have finished my homework. So have I.", ["did"], ["I have done my homework. So have I."]),
    s("Men ertaga uyda bo'laman. - Men ham.", "I will be at home tomorrow. So will I.", ["am"], ["I will be home tomorrow. So will I."]),
    s("Ular ziyofatga bormadi. - Biz ham.", "They didn't go to the party. Neither did we.", ["so"], ["They didn't go to the party. Nor did we."]),
    s("Kamola o'tgan hafta Buxoroda edi. - Jasur ham.", "Kamola was in Bukhara last week. So was Jasur.", ["did"]),
    s("Singlim shokoladni yaxshi ko'radi. - Akam ham.", "My sister loves chocolate. So does my brother.", ["do"], [
      "My sister likes chocolate. So does my brother.",
      "My younger sister loves chocolate. So does my older brother.",
      "My younger sister likes chocolate. So does my older brother.",
    ]),
    s("Men ertalab nonushta qilmayman. - Men ham.", "I don't have breakfast in the morning. Neither do I.", ["so"], [
      "I don't have breakfast in the morning. Nor do I.",
      "I don't eat breakfast in the morning. Neither do I.",
      "I don't eat breakfast in the morning. Nor do I.",
    ]),
  ],
};

/* ───────────────────────────── 20. Verb patterns ───────────────────────────── */

const VERB_PATTERNS: GrammarTopicContent = {
  slug: "a2-verb-patterns",
  level: "A2",
  position: 20,
  title: { en: "want / ask / tell someone to do; make / let someone do", uz: "want / ask / tell + kimdir + to; make / let + kimdir + fe'l" },
  explanation: {
    uz: [
      "want / would like / ask / tell + kimdir + to + fe'l: I want you to help me = Menga yordam berishingni xohlayman.",
      "O'zbekcha \"sening kelishingni xohlayman\" deymiz, inglizcha esa I want you to come (I want that you come emas).",
      "Olmosh obyekt shaklda bo'ladi: me, you, him, her, us, them: She asked me to wait (asked I emas).",
      "Inkor: tell / ask + kimdir + not to + fe'l: The teacher told us not to talk = O'qituvchi bizga gaplashmaslikni aytdi.",
      "make + kimdir + fe'l (to'siz) = majbur qilmoq: My mum made me clean my room = Onam meni xonamni tozalashga majbur qildi.",
      "let + kimdir + fe'l (to'siz) = ruxsat bermoq: Let me help you. My parents let me go out.",
      "O'tgan zamon: wanted, asked, told, made, let (let o'zgarmaydi).",
    ].join("\n"),
    pattern: "want / would like / ask / tell + object + to + verb · ask / tell + object + not to + verb · make / let + object + verb (no to)",
    examples: [
      { en: "I want you to come.", uz: "Men sening kelishingni xohlayman." },
      { en: "The teacher told us not to talk.", uz: "O'qituvchi bizga gaplashmaslikni aytdi." },
      { en: "My mum made me clean my room.", uz: "Onam meni xonamni tozalashga majbur qildi." },
      { en: "Let me help you.", uz: "Ruxsat bering, sizga yordam beray." },
    ],
  },
  build: [
    s("Men sening kelishingni xohlayman.", "I want you to come.", ["that"]),
    s("Onam mening shifokor bo'lishimni xohlaydi.", "My mother wants me to be a doctor.", ["I"], [
      "My mum wants me to be a doctor.",
      "My mom wants me to be a doctor.",
    ]),
    s("U (yigit) mening unga yordam berishimni xohlaydi.", "He wants me to help him.", ["I"]),
    s("Ular bizning qolishimizni xohlashadi.", "They want us to stay.", ["we"]),
    s("O'qituvchi bizning ko'proq kitob o'qishimizni xohlaydi.", "The teacher wants us to read more books.", ["we"]),
    s("Sen bilan borishimni xohlaysanmi?", "Do you want me to go with you?", ["I"], ["Do you want me to come with you?"]),
    s("Men sizning uchrashuvga kelishingizni istardim.", "I would like you to come to the meeting.", ["that"]),
    s("Ali sizning unga qo'ng'iroq qilishingizni istaydi.", "Ali would like you to call him.", ["he"], [
      "Ali would like you to phone him.",
      "Ali wants you to call him.",
      "Ali wants you to phone him.",
    ]),
    s("Malika mendan eshikni yopishimni so'radi.", "Malika asked me to close the door.", ["I"], ["Malika asked me to shut the door."]),
    s("Men undan (qizdan) kutib turishini so'radim.", "I asked her to wait.", ["she"]),
    s("O'qituvchi bizdan jim bo'lishimizni so'radi.", "The teacher asked us to be quiet.", ["we"]),
    s("Otam menga uy vazifamni qilishimni aytdi.", "My father told me to do my homework.", ["said"], ["My dad told me to do my homework."]),
    s("Shifokor unga (yigitga) ko'proq dam olishni aytdi.", "The doctor told him to rest more.", ["he"]),
    s("Men ularga ertaroq kelishlarini aytdim.", "I told them to come early.", ["they"], ["I told them to come earlier."]),
    s("O'qituvchi bizga gaplashmaslikni aytdi.", "The teacher told us not to talk.", ["don't"], ["The teacher told us not to speak."]),
    s("Onam mendan kechikmasligimni so'radi.", "My mother asked me not to be late.", ["don't"], [
      "My mum asked me not to be late.",
      "My mom asked me not to be late.",
    ]),
    s("Onam meni xonamni tozalashga majbur qildi.", "My mum made me clean my room.", ["to"], [
      "My mom made me clean my room.",
      "My mother made me clean my room.",
    ]),
    s("O'qituvchi bizni hamma narsani qayta yozishga majbur qildi.", "The teacher made us write everything again.", ["to"]),
    s("Bu film meni yig'latdi.", "This film made me cry.", ["to"], ["This movie made me cry."]),
    s("Ular meni uzoq kutishga majbur qilishdi.", "They made me wait for a long time.", ["to"], ["They made me wait a long time."]),
    s("Ruxsat bering, sizga yordam beray.", "Let me help you.", ["to"]),
    s("Ruxsat bering, o'zimni tanishtiray.", "Let me introduce myself.", ["to"]),
    s("Ota-onam menga kechqurun tashqariga chiqishimga ruxsat berishadi.", "My parents let me go out in the evening.", ["to"], [
      "My parents let me go out in the evenings.",
    ]),
    s("Otam menga mashinasini haydashimga ruxsat bermaydi.", "My father doesn't let me drive his car.", ["to"], [
      "My dad doesn't let me drive his car.",
    ]),
    s("O'qituvchi bizga erta ketishimizga ruxsat berdi.", "The teacher let us leave early.", ["to"], ["The teacher let us go early."]),
    s("Ular bizni ichkariga kiritishmadi.", "They didn't let us go in.", ["to"], ["They didn't let us in.", "They didn't let us come in."]),
    s("Onam meni sabzavot yeyishga majbur qiladi.", "My mother makes me eat vegetables.", ["to"], [
      "My mum makes me eat vegetables.",
      "My mom makes me eat vegetables.",
    ]),
    s("Jasur mendan unga pul qarz berishimni so'radi.", "Jasur asked me to lend him some money.", ["I"], ["Jasur asked me to lend him money."]),
    s("Men sening menga haqiqatni aytishingni xohlayman.", "I want you to tell me the truth.", ["that"]),
    s("Boshliq bizdan ertaga soat sakkizda kelishimizni so'radi.", "The boss asked us to come at eight tomorrow.", ["we"], [
      "The boss asked us to come at eight o'clock tomorrow.",
      "The boss asked us to come tomorrow at eight.",
      "The boss asked us to come tomorrow at eight o'clock.",
      "Our boss asked us to come at eight tomorrow.",
      "Our boss asked us to come at eight o'clock tomorrow.",
      "Our boss asked us to come tomorrow at eight.",
      "Our boss asked us to come tomorrow at eight o'clock.",
    ]),
  ],
  test: [
    s("Men sening qolishingni xohlayman.", "I want you to stay.", ["that"]),
    s("Otam mening muhandis bo'lishimni xohlaydi.", "My father wants me to be an engineer.", ["I"], ["My dad wants me to be an engineer."]),
    s("Ular bizning ularga yordam berishimizni xohlashadi.", "They want us to help them.", ["we"]),
    s("Derazani ochishimni xohlaysizmi?", "Do you want me to open the window?", ["I"]),
    s("Men sizning ziyofatimga kelishingizni istardim.", "I would like you to come to my party.", ["that"]),
    s("Zarina mendan unga yordam berishimni so'radi.", "Zarina asked me to help her.", ["I"]),
    s("Men undan (yigitdan) telefonini o'chirishini so'radim.", "I asked him to turn off his phone.", ["he"], [
      "I asked him to switch off his phone.",
      "I asked him to turn his phone off.",
      "I asked him to switch his phone off.",
    ]),
    s("Onam menga non sotib olishimni aytdi.", "My mother told me to buy bread.", ["said"], [
      "My mum told me to buy bread.",
      "My mom told me to buy bread.",
      "My mother told me to buy some bread.",
      "My mum told me to buy some bread.",
      "My mom told me to buy some bread.",
    ]),
    s("Politsiyachi bizga to'xtashimizni aytdi.", "The police officer told us to stop.", ["we"], ["The policeman told us to stop."]),
    s("Shifokor menga shirinlik yemaslikni aytdi.", "The doctor told me not to eat sweets.", ["don't"], ["The doctor told me not to eat candy."]),
    s("U (qiz) mendan hech kimga aytmasligimni so'radi.", "She asked me not to tell anyone.", ["don't"], ["She asked me not to tell anybody."]),
    s("Otam meni erta turishga majbur qiladi.", "My father makes me get up early.", ["to"], [
      "My dad makes me get up early.",
      "My father makes me wake up early.",
      "My dad makes me wake up early.",
    ]),
    s("Bu hikoya meni kuldirdi.", "This story made me laugh.", ["to"]),
    s("O'qituvchi meni uy vazifamni qayta qilishga majbur qildi.", "The teacher made me do my homework again.", ["to"]),
    s("Ruxsat bering, ko'ray.", "Let me see.", ["to"], ["Let me look."]),
    s("Ruxsat bering, sumkangizni ko'taray.", "Let me carry your bag.", ["to"]),
    s("Ota-onam dam olish kunlari kompyuter o'yinlari o'ynashimga ruxsat berishadi.", "My parents let me play computer games at the weekend.", ["to"], [
      "My parents let me play computer games at weekends.",
      "My parents let me play computer games on weekends.",
      "My parents let me play computer games on the weekend.",
      "My parents let me play computer games on the weekends.",
    ]),
    s("Ular bizga suratga olishimizga ruxsat berishmadi.", "They didn't let us take photos.", ["to"], [
      "They didn't let us take pictures.",
      "They didn't let us take photographs.",
    ]),
    s("Sardor mendan uning mushugiga qarab turishimni so'radi.", "Sardor asked me to look after his cat.", ["I"], [
      "Sardor asked me to take care of his cat.",
    ]),
    s("Menejer bizni shanba kuni ham ishlashga majbur qildi.", "The manager made us work on Saturday too.", ["to"], [
      "The manager made us work on Saturday as well.",
      "The manager also made us work on Saturday.",
    ]),
  ],
};

export const A2_PART4_TOPICS: GrammarTopicContent[] = [
  PASSIVE,
  RELATIVE_CLAUSES,
  SUBJECT_OBJECT_QUESTIONS,
  SO_NEITHER,
  VERB_PATTERNS,
];
